In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

import warnings
warnings.filterwarnings("ignore")

from webdriver_manager.chrome import ChromeDriverManager

In [2]:
driver = webdriver.Chrome(ChromeDriverManager().install())

====== WebDriver manager ======
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\HP\.wdm\drivers\chromedriver\win32\101.0.4951.41]

In [3]:
url = 'https://www.cleartrip.com/'
driver.get(url)

In [4]:
city=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[3]/div[1]/div[1]/div/div/div[1]/input")
city.send_keys('mumbai')

In [5]:
click=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[3]/div[1]/div[1]/div/div/div[2]/ul/li/p")
click.click()

In [6]:
city1=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[3]/div[1]/div[5]/div/div/div[1]/input")
city1.send_keys('London')

In [7]:
click=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[3]/div[1]/div[5]/div/div/div[2]/ul/li[1]/p")
click.click()

In [8]:
button=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[3]/div[3]/div/div/div/div/button[1]")
button.click()

In [10]:
date=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[3]/div[3]/div/div/div/div/div/ul/div[2]/div/div[2]/div[1]/div[3]/div[5]/div[6]/div/div")
date.click()

In [11]:
search=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[7]/div[2]/button")
search.click()

In [132]:
# Mumbai-London Flight Details

In [15]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("//span[@class='bg-warning-100 br-100 fw-600 fs-2 lh-copy px-2 py-0']")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('1 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [16]:
df['Date Of Journey'] = '30 Apr'
df

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,03:10,20:00,21h 20m,1 stop,"₹64,734",30 Apr
1,Vistara,BOM,LHR,BOM → DEL → LHR,06:30,19:50,17h 50m,1 stop,"₹68,365",30 Apr
2,Vistara,BOM,LHR,BOM → DEL → LHR,08:45,19:50,15h 35m,1 stop,"₹68,770",30 Apr
3,Air India,BOM,LHR,BOM → IDR → DEL → LHR,07:05,19:00,16h 25m,2 stops,"₹69,655",30 Apr
4,Emirates,BOM,LGW,BOM → DXB → LGW,19:20,12:35,21h 45m,1 stop,"₹71,648",30 Apr
5,Emirates,BOM,LGW,BOM → DXB → LGW,10:10,18:35,12h 55m,1 stop,"₹75,549",30 Apr
6,Vistara,BOM,LHR,BOM → HYD → DEL → LHR,06:20,19:50,18h 0m,2 stops,"₹76,850",30 Apr
7,Air India,BOM,LHR,BOM → LHR,06:30,11:30,9h 30m,non-stop,"₹76,904",30 Apr
8,Vistara,BOM,LHR,BOM → DEL → LHR,10:25,19:50,13h 55m,1 stop,"₹77,280",30 Apr
9,Vistara,BOM,LHR,BOM → DEL → LHR,22:45,19:50,25h 35m,1 stop,"₹77,815",30 Apr
10,Air India,BOM,LHR,BOM → GOI → DEL → LHR,21:00,10:152 May,41h 45m,2 stops,"₹79,840",30 Apr
11,Air India,BOM,LHR,BOM → ATQ → LHR,05:55,09:55,32h 30m,1 stop,"₹80,575",30 Apr
12,Virgin Atlantic,BOM,LHR,BOM → LHR,12:10,17:30,9h 50m,non-stop,"₹81,985",30 Apr
13,Multiple carrier,BOM,LGW,BOM → DOH → LGW,18:35,06:20,16h 15m,1 stop,"₹83,065",30 Apr
14,Kuwait Airways,BOM,LHR,BOM → KWI → LHR,06:20,14:45,12h 55m,1 stop,"₹87,533",30 Apr
15,Saudi Arabian Air,BOM,LHR,BOM → RUH → LHR,08:25,17:40,13h 45m,1 stop,"₹88,296",30 Apr
16,Air India,BOM,LHR,BOM → GOI → DEL → LHR,21:00,19:002 May,50h 30m,2 stops,"₹88,660",30 Apr
17,Air France,BOM,LHR,BOM → CDG → LHR,02:10,16:35,18h 55m,1 stop,"₹94,492",30 Apr
18,Air France,BOM,LHR,BOM → CDG → LHR,02:10,21:20,23h 40m,1 stop,"₹94,623",30 Apr
19,Emirates,BOM,LHR,BOM → DXB → LHR,22:20,16:10,22h 20m,1 stop,"₹98,948",30 Apr
20,Lufthansa,BOM,LHR,BOM → MUC → LHR,00:50,08:15,11h 55m,1 stop,"₹1,09,585",30 Apr
21,Gulf Air,BOM,LHR,BOM → BAH → LHR,21:45,15:20,22h 5m,1 stop,"₹1,11,665",30 Apr
22,Turkish Airlines,BOM,STN,BOM → IST → SAW → STN,06:25,22:10,20h 15m,1 stop,"₹1,14,112",30 Apr
23,Lufthansa,BOM,LHR,BOM → MUC → BRU → LHR,00:50,10:15,13h 55m,2 stops,"₹1,15,072",30 Apr
24,Lufthansa,BOM,LHR,BOM → MUC → FRA → LHR,00:50,10:40,14h 20m,2 stops,"₹1,15,159",30 Apr
25,Lufthansa,BOM,LHR,BOM → MUC → FRA → LHR,00:50,17:40,21h 20m,2 stops,"₹1,17,954",30 Apr
26,Air India,BOM,LHR,BOM → DEL → LHR,10:00,19:00,13h 30m,1 stop,"₹1,18,215",30 Apr
27,Multiple carrier,BOM,LHR,BOM → BLR → CDG → LHR,21:30,10:30,17h 30m,2 stops,"₹1,19,824",30 Apr
28,Air France,BOM,LHR,BOM → CDG → LHR,02:10,10:30,12h 50m,1 stop,"₹1,20,396",30 Apr
29,Emirates,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹1,31,813",30 Apr
30,Air India,BOM,LHR,BOM → DEL → LHR,19:00,07:30,17h 0m,1 stop,"₹1,36,330",30 Apr
31,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,06:25,16h 20m,1 stop,"₹1,41,461",30 Apr
32,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,14:10,24h 5m,1 stop,"₹1,41,736",30 Apr
33,Etihad Airways,BOM,LHR,BOM → AUH → LHR,20:55,06:45,14h 20m,1 stop,"₹1,42,575",30 Apr
34,Multiple carrier,BOM,LHR,BOM → DEL → LHR,06:00,15:20,13h 50m,1 stop,"₹1,44,105",30 Apr
35,British Airways,BOM,LHR,BOM → LHR,13:10,18:25,9h 45m,non-stop,"₹1,45,804",30 Apr
36,Air India,BOM,LHR,BOM → GOI → DEL → LHR,05:05,07:30,30h 55m,2 stops,"₹1,46,305",30 Apr
37,Emirates,BOM,LHR,BOM → DXB → LHR,05:10,14:25,13h 45m,1 stop,"₹1,47,905",30 Apr
38,Air India,BOM,LHR,BOM → BLR → DEL → LHR,06:10,07:30,29h 50m,2 stops,"₹1,48,090",30 Apr
39,Air India,BOM,LHR,BOM → BLR → DEL → LHR,09:30,07:30,26h 30m,2 stops,"₹1,48,300",30 Apr
40,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:55,14:10,13h 45m,1 stop,"₹1,63,873",30 Apr
41,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,13:10,23h 5m,1 stop,"₹1,64,148",30 Apr
42,Multiple carrier,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹1,68,090",30 Apr
43,Multiple carrier,BOM,LGW,BOM → DXB → LGW,08:25,18:35,14h 40m,1 stop,"₹1,69,221",30 Apr
44,Multiple carrier,BOM,LGW,BOM → DXB → LGW,16:25,12:35,24h 40m,1 stop,"₹1,69,221",30 Apr
45,Multiple carrier,BOM,LHR,BOM → DOH → LHR,04:25,14:10,14h 15m,1 stop,"₹1,76,404",30 Apr
46,Air India,BOM,LHR,BOM → DEL → LHR,10:00,07:30,26h 0m,1 stop,"₹1,84,890",30 Apr
47,Air India,BOM,LHR,BOM → BLR → DEL → LHR,09:30,07:30,26h 30m,2 stops,"₹2,01,608",30 Apr
48,Gulf Air,BOM,LHR,BOM → BAH → LHR,21:45,06:55,13h 40m,1 stop,"₹2,58,390",30 Apr
49,Emirates,BOM,LHR,BOM → DXB → LHR,22:20,07:05,13h 15m,1 stop,"₹3,23,006",30 Apr
50,Multiple carrier,BOM,LCY,BOM → DEL → AMS → LCY,18:30,17:20,27h 20m,2 stops,"₹3,61,802",30 Apr
51,KLM Royal Dutch,BOM,LHR,BOM → CDG → AMS → LHR,02:10,19:25,21h 45m,2 stops,"₹3,63,795",30 Apr
52,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:25,13:10,13h 15m,1 stop,"₹4,10,483",30 Apr
53,Singapore Air,BOM,LHR,BOM → SIN → LHR,11:45,05:55,22h 40m,1 stop,"₹4,63,244",30 Apr
54,Multiple carrier,BOM,LHR,BOM → DOH → LHR,04:25,13:10,13h 15m,1 stop,"₹5,97,456",30 Apr
55,Multiple carrier,BOM,LHR,BOM → BAH → LHR,21:45,06:15,13h 0m,1 stop,"₹6,16,618",30 Apr

In [17]:
search=driver.find_element_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[5]/div/div[2]")
search.click()

In [18]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("//span[@class='bg-warning-100 br-100 fw-600 fs-2 lh-copy px-2 py-0']")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('2 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df2=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [19]:
df2['Date Of Journey'] = '01 May'
df2

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,20:40,20:00,27h 50m,1 stop,"₹56,385",01 May
1,Air India,BOM,LHR,BOM → DEL → LHR,19:00,10:15,19h 45m,1 stop,"₹69,655",01 May
2,Emirates,BOM,LGW,BOM → DXB → LGW,04:30,12:35,12h 35m,1 stop,"₹75,549",01 May
3,Vistara,BOM,LHR,BOM → DEL → LHR,08:45,19:50,15h 35m,1 stop,"₹77,815",01 May
4,Air India,BOM,LHR,BOM → DEL → LHR,19:00,19:00,28h 30m,1 stop,"₹78,475",01 May
5,Vistara,BOM,LHR,BOM → DEL → LHR,10:25,19:50,13h 55m,1 stop,"₹78,781",01 May
6,Kuwait Airways,BOM,LHR,BOM → KWI → LHR,02:25,10:00,12h 5m,1 stop,"₹79,254",01 May
7,Air India,BOM,LHR,BOM → GOI → DEL → LHR,05:05,10:15,33h 40m,2 stops,"₹79,630",01 May
8,Air India,BOM,LHR,BOM → GOI → DEL → LHR,21:00,10:15,17h 45m,2 stops,"₹79,840",01 May
9,Oman Av (SAOG),BOM,LHR,BOM → MCT → LHR,10:30,19:10,13h 10m,1 stop,"₹80,193",01 May
10,Air India,BOM,LHR,BOM → BLR → DEL → LHR,06:50,10:15,31h 55m,2 stops,"₹81,415",01 May
11,Air India,BOM,LHR,BOM → BLR → DEL → LHR,09:30,10:15,29h 15m,2 stops,"₹81,625",01 May
12,Vistara,BOM,LHR,BOM → HYD → DEL → LHR,06:20,19:50,18h 0m,2 stops,"₹85,738",01 May
13,Kenya Airways,BOM,LHR,BOM → NBO → LHR,16:45,16:15,28h 0m,1 stop,"₹86,496",01 May
14,Kuwait Airways,BOM,LHR,BOM → KWI → LHR,06:20,14:45,12h 55m,1 stop,"₹87,533",01 May
15,Air India,BOM,LHR,BOM → LHR,06:30,11:30,9h 30m,non-stop,"₹88,559",01 May
16,Multiple carrier,BOM,LGW,BOM → DOH → LGW,18:35,06:20,16h 15m,1 stop,"₹98,804",01 May
17,Emirates,BOM,LGW,BOM → DXB → LGW,10:10,19:45,14h 5m,1 stop,"₹98,948",01 May
18,Singapore Air,BOM,LHR,BOM → SIN → LHR,23:40,15:40,20h 30m,1 stop,"₹1,00,977",01 May
19,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,06:25,16h 20m,1 stop,"₹1,04,685",01 May
20,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,14:10,24h 5m,1 stop,"₹1,04,960",01 May
21,Turkish Airlines,BOM,STN,BOM → IST → SAW → STN,06:25,22:10,20h 15m,1 stop,"₹1,14,112",01 May
22,Emirates,BOM,LHR,BOM → DXB → LHR,05:10,16:10,15h 30m,1 stop,"₹1,15,040",01 May
23,Air France,BOM,LHR,BOM → CDG → LHR,02:10,10:30,12h 50m,1 stop,"₹1,20,396",01 May
24,Air France,BOM,LHR,BOM → CDG → LHR,02:10,21:20,23h 40m,1 stop,"₹1,20,527",01 May
25,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:55,14:10,13h 45m,1 stop,"₹1,22,204",01 May
26,Virgin Atlantic,BOM,LHR,BOM → LHR,12:15,17:35,9h 50m,non-stop,"₹1,28,810",01 May
27,Air India,BOM,LHR,BOM → HYD → LHR,20:10,07:30,15h 50m,1 stop,"₹1,31,288",01 May
28,Emirates,BOM,LHR,BOM → DXB → LHR,10:10,18:40,13h 0m,1 stop,"₹1,31,813",01 May
29,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,13:10,23h 5m,1 stop,"₹1,41,736",01 May
30,Etihad Airways,BOM,LHR,BOM → AUH → LHR,04:35,12:50,12h 45m,1 stop,"₹1,42,575",01 May
31,British Airways,BOM,LHR,BOM → LHR,13:10,18:25,9h 45m,non-stop,"₹1,45,804",01 May
32,Emirates,BOM,LHR,BOM → DXB → LHR,05:10,14:25,13h 45m,1 stop,"₹1,47,905",01 May
33,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:25,14:10,14h 15m,1 stop,"₹1,63,873",01 May
34,Thai Airways,BOM,LHR,BOM → BKK → HKT → LHR,23:35,19:10,24h 5m,2 stops,"₹1,65,986",01 May
35,Multiple carrier,BOM,LGW,BOM → DXB → LGW,04:30,12:35,12h 35m,1 stop,"₹1,68,090",01 May
36,Saudi Arabian Air,BOM,LHR,BOM → JED → LHR,04:10,13:45,14h 5m,1 stop,"₹1,76,358",01 May
37,Multiple carrier,BOM,LHR,BOM → DOH → LHR,04:25,14:10,14h 15m,1 stop,"₹1,76,404",01 May
38,Multiple carrier,BOM,LHR,BOM → DXB → LHR,20:20,05:55,14h 5m,1 stop,"₹2,16,210",01 May
39,Gulf Air,BOM,LHR,BOM → BAH → LHR,21:45,06:55,13h 40m,1 stop,"₹2,41,749",01 May
40,Multiple carrier,BOM,LHR,BOM → DEL → LHR,22:45,07:50,13h 35m,1 stop,"₹3,15,324",01 May
41,Emirates,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹3,23,006",01 May
42,KLM Royal Dutch,BOM,LHR,BOM → AMS → LHR,02:20,10:45,12h 55m,1 stop,"₹3,62,364",01 May
43,KLM Royal Dutch,BOM,LCY,BOM → CDG → AMS → LCY,02:10,13:15,15h 35m,2 stops,"₹3,63,795",01 May
44,Multiple carrier,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹4,07,793",01 May
45,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:25,13:10,13h 15m,1 stop,"₹4,10,483",01 May
46,Multiple carrier,BOM,LHR,BOM → DOH → LHR,04:25,13:10,13h 15m,1 stop,"₹5,97,456",01 May

In [20]:
search=driver.find_element_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[5]/div/div[3]")
search.click()

In [21]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("//span[@class='bg-warning-100 br-100 fw-600 fs-2 lh-copy px-2 py-0']")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('3 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df3=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [22]:
df3['Date Of Journey'] = '02 May'
df3

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,03:10,20:00,21h 20m,1 stop,"₹56,385",02 May
1,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,20:40,20:00,27h 50m,1 stop,"₹64,734",02 May
2,Vistara,BOM,LHR,BOM → DEL → LHR,22:45,19:50,25h 35m,1 stop,"₹68,365",02 May
3,Air India,BOM,LHR,BOM → DEL → LHR,19:00,19:00,28h 30m,1 stop,"₹69,655",02 May
4,Ethiopian Air,BOM,LHR,BOM → ADD → LHR,04:05,17:00,17h 25m,1 stop,"₹73,040",02 May
5,Vistara,BOM,LHR,BOM → DEL → LHR,10:25,19:50,13h 55m,1 stop,"₹77,815",02 May
6,Vistara,BOM,LHR,BOM → DEL → LHR,08:45,19:50,15h 35m,1 stop,"₹78,057",02 May
7,Vistara,BOM,LHR,BOM → DEL → LHR,06:30,19:50,17h 50m,1 stop,"₹78,220",02 May
8,Air India,BOM,LHR,BOM → DEL → LHR,10:00,19:00,13h 30m,1 stop,"₹78,475",02 May
9,Air India,BOM,LHR,BOM → GOI → DEL → LHR,21:00,19:00,26h 30m,2 stops,"₹79,630",02 May
10,Oman Av (SAOG),BOM,LHR,BOM → MCT → LHR,10:30,19:10,13h 10m,1 stop,"₹80,193",02 May
11,Air India,BOM,LHR,BOM → BLR → DEL → LHR,16:40,19:00,30h 50m,2 stops,"₹81,415",02 May
12,Vistara,BOM,LHR,BOM → HYD → DEL → LHR,06:20,19:50,18h 0m,2 stops,"₹85,575",02 May
13,Kuwait Airways,BOM,LHR,BOM → KWI → LHR,06:20,14:45,12h 55m,1 stop,"₹87,533",02 May
14,Air India,BOM,LHR,BOM → LHR,10:15,15:15,9h 30m,non-stop,"₹88,559",02 May
15,Air India,BOM,LHR,BOM → AMD → LHR,18:35,11:30,21h 25m,1 stop,"₹90,130",02 May
16,Air India,BOM,LHR,BOM → BLR → DEL → LHR,09:30,07:30,26h 30m,2 stops,"₹90,235",02 May
17,Singapore Air,BOM,LHR,BOM → SIN → LHR,23:40,15:40,20h 30m,1 stop,"₹1,00,977",02 May
18,Swiss Intl Air,BOM,LHR,BOM → ZRH → LHR,05:15,13:00,12h 15m,1 stop,"₹1,07,791",02 May
19,Gulf Air,BOM,LHR,BOM → BAH → LHR,06:30,15:20,13h 20m,1 stop,"₹1,10,982",02 May
20,Air India,BOM,LHR,BOM → GOI → LHR,21:00,10:15,17h 45m,1 stop,"₹1,16,483",02 May
21,Virgin Atlantic,BOM,LHR,BOM → LHR,12:15,17:35,9h 50m,non-stop,"₹1,28,810",02 May
22,Emirates,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹1,29,766",02 May
23,Multiple carrier,BOM,LHR,BOM → DEL → LHR,22:45,07:50,13h 35m,1 stop,"₹1,44,105",02 May
24,Emirates,BOM,LHR,BOM → DXB → LHR,05:10,14:25,13h 45m,1 stop,"₹1,45,857",02 May
25,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:55,14:10,13h 45m,1 stop,"₹1,61,243",02 May
26,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,14:10,24h 5m,1 stop,"₹1,61,518",02 May
27,British Airways,BOM,LHR,BOM → LHR,13:10,18:25,9h 45m,non-stop,"₹1,66,656",02 May
28,Multiple carrier,BOM,LGW,BOM → DXB → LGW,04:30,12:35,12h 35m,1 stop,"₹1,68,090",02 May
29,Multiple carrier,BOM,LHR,BOM → DOH → LHR,04:25,14:10,14h 15m,1 stop,"₹1,73,774",02 May
30,Multiple carrier,BOM,LHR,BOM → BAH → LHR,21:45,06:15,13h 0m,1 stop,"₹1,98,338",02 May
31,Multiple carrier,BOM,LHR,BOM → DXB → LHR,20:20,05:55,14h 5m,1 stop,"₹2,16,210",02 May
32,Etihad Airways,BOM,LHR,BOM → AUH → LHR,04:35,12:50,12h 45m,1 stop,"₹2,22,057",02 May
33,Lufthansa,BOM,LHR,BOM → MUC → LHR,00:50,08:15,11h 55m,1 stop,"₹2,48,793",02 May
34,Gulf Air,BOM,LHR,BOM → BAH → LHR,21:45,06:55,13h 40m,1 stop,"₹2,57,702",02 May
35,Emirates,BOM,LHR,BOM → DXB → LHR,10:10,18:40,13h 0m,1 stop,"₹3,19,086",02 May
36,Multiple carrier,BOM,LHR,BOM → RUH → LHR,12:30,06:20,22h 20m,1 stop,"₹4,10,784",02 May

In [23]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("//span[@class='bg-warning-100 br-100 fw-600 fs-2 lh-copy px-2 py-0']")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('4 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df4=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [24]:
df4['Date Of Journey'] = '03 May'
df4

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,03:10,20:00,21h 20m,1 stop,"₹64,734",03 May
1,Air India,BOM,LHR,BOM → LHR,15:00,20:00,9h 30m,non-stop,"₹68,084",03 May
2,Vistara,BOM,LHR,BOM → DEL → LHR,10:25,19:50,13h 55m,1 stop,"₹68,365",03 May
3,Vistara,BOM,LHR,BOM → DEL → LHR,08:45,19:50,15h 35m,1 stop,"₹68,607",03 May
4,Air India,BOM,LHR,BOM → DEL → LHR,10:00,19:00,13h 30m,1 stop,"₹69,655",03 May
5,Ethiopian Air,BOM,LHR,BOM → ADD → LHR,04:05,17:00,17h 25m,1 stop,"₹73,040",03 May
6,Emirates,BOM,LGW,BOM → DXB → LGW,22:20,12:35,18h 45m,1 stop,"₹73,502",03 May
7,Vistara,BOM,LHR,BOM → HYD → DEL → LHR,06:20,19:50,18h 0m,2 stops,"₹75,884",03 May
8,Kuwait Airways,BOM,LHR,BOM → KWI → LHR,02:25,14:45,16h 50m,1 stop,"₹79,254",03 May
9,Air India,BOM,LHR,BOM → GOI → DEL → LHR,05:05,07:30,30h 55m,2 stops,"₹79,630",03 May
10,Air India,BOM,LHR,BOM → BLR → DEL → LHR,16:40,07:30,19h 20m,2 stops,"₹81,415",03 May
11,Egypt Air,BOM,LHR,BOM → CAI → LHR,03:00,13:35,15h 5m,1 stop,"₹81,607",03 May
12,Kenya Airways,BOM,LHR,BOM → NBO → LHR,02:25,16:15,18h 20m,1 stop,"₹86,496",03 May
13,Gulf Air,BOM,LHR,BOM → BAH → LHR,21:45,15:20,22h 5m,1 stop,"₹89,331",03 May
14,Emirates,BOM,LHR,BOM → DXB → LHR,22:20,07:05,13h 15m,1 stop,"₹96,901",03 May
15,Singapore Air,BOM,LHR,BOM → SIN → LHR,23:40,15:40,20h 30m,1 stop,"₹1,00,977",03 May
16,Virgin Atlantic,BOM,LHR,BOM → LHR,12:15,17:35,9h 50m,non-stop,"₹1,09,086",03 May
17,Lufthansa,BOM,LHR,BOM → FRA → LHR,02:50,10:40,12h 20m,1 stop,"₹1,10,008",03 May
18,Air India,BOM,LHR,BOM → HYD → LHR,20:10,11:30,19h 50m,1 stop,"₹1,10,813",03 May
19,Lufthansa,BOM,LCY,BOM → FRA → LCY,02:50,07:15,32h 55m,1 stop,"₹1,10,888",03 May
20,Multiple carrier,BOM,LCY,BOM → BLR → FRA → LCY,21:30,16:25,23h 25m,2 stops,"₹1,12,231",03 May
21,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:55,18:00,17h 35m,1 stop,"₹1,19,574",03 May
22,Multiple carrier,BOM,LHR,BOM → BLR → CDG → LHR,21:30,10:30,17h 30m,2 stops,"₹1,19,824",03 May
23,Air France,BOM,LHR,BOM → CDG → LHR,02:10,16:35,18h 55m,1 stop,"₹1,20,396",03 May
24,Air France,BOM,LHR,BOM → CDG → LHR,02:10,21:20,23h 40m,1 stop,"₹1,20,527",03 May
25,KLM Royal Dutch,BOM,LCY,BOM → CDG → AMS → LCY,02:10,16:40,19h 0m,2 stops,"₹1,21,785",03 May
26,Multiple carrier,BOM,LCY,BOM → CDG → AMS → LCY,02:10,16:40,19h 0m,2 stops,"₹1,22,970",03 May
27,Emirates,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹1,29,766",03 May
28,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:55,14:10,13h 45m,1 stop,"₹1,38,836",03 May
29,Etihad Airways,BOM,LHR,BOM → AUH → LHR,20:55,06:45,14h 20m,1 stop,"₹1,40,853",03 May
30,Multiple carrier,BOM,LHR,BOM → DEL → LHR,22:45,07:50,13h 35m,1 stop,"₹1,44,105",03 May
31,Multiple carrier,BOM,LGW,BOM → DOH → LGW,18:35,06:20,16h 15m,1 stop,"₹1,53,055",03 May
32,Qatar Airways,BOM,LHR,BOM → DOH → LHR,04:25,14:10,14h 15m,1 stop,"₹1,61,243",03 May
33,British Airways,BOM,LHR,BOM → LHR,13:10,18:25,9h 45m,non-stop,"₹1,66,656",03 May
34,Multiple carrier,BOM,LHR,BOM → DXB → LHR,22:20,07:05,13h 15m,1 stop,"₹1,67,133",03 May
35,Multiple carrier,BOM,LHR,BOM → DXB → LHR,04:30,12:25,12h 25m,1 stop,"₹1,68,090",03 May
36,Multiple carrier,BOM,LGW,BOM → DXB → LGW,01:05,12:35,16h 0m,1 stop,"₹1,69,221",03 May
37,Multiple carrier,BOM,LGW,BOM → DXB → LGW,23:05,12:35,18h 0m,1 stop,"₹1,69,221",03 May
38,Multiple carrier,BOM,LHR,BOM → DOH → LHR,04:25,14:10,14h 15m,1 stop,"₹1,73,774",03 May
39,Multiple carrier,BOM,LHR,BOM → BAH → LHR,21:45,06:15,13h 0m,1 stop,"₹1,98,338",03 May
40,Turkish Airlines,BOM,LGW,BOM → IST → LGW,06:25,16:20,14h 25m,1 stop,"₹2,07,232",03 May
41,Gulf Air,BOM,LHR,BOM → BAH → LHR,06:30,15:20,13h 20m,1 stop,"₹2,57,702",03 May

In [25]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("//span[@class='bg-warning-100 br-100 fw-600 fs-2 lh-copy px-2 py-0']")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('4 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df5=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [26]:
df5['Date Of Journey'] = '04 May'
df5

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,20:40,20:005 May,27h 50m,1 stop,"₹49,236",04 May
1,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,03:10,20:00,21h 20m,1 stop,"₹56,385",04 May
2,Gulf Air,BOM,LHR,BOM → BAH → LHR,21:45,06:555 May,13h 40m,1 stop,"₹61,716",04 May
3,Etihad Airways,BOM,LHR,BOM → AUH → LHR,20:55,06:455 May,14h 20m,1 stop,"₹64,975",04 May
4,Emirates,BOM,LGW,BOM → DXB → LGW,05:10,19:45,19h 5m,1 stop,"₹66,477",04 May
...,...,...,...,...,...,...,...,...,...,...
56,Multiple carrier,BOM,LCY,BOM → DEL → AMS → LCY,22:45,16:405 May,22h 25m,2 stops,"₹3,61,802",04 May
57,KLM Royal Dutch,BOM,LCY,BOM → AMS → LCY,02:20,08:50,11h 0m,1 stop,"₹3,62,364",04 May
58,KLM Royal Dutch,BOM,LCY,BOM → CDG → AMS → LCY,02:10,16:40,19h 0m,2 stops,"₹3,63,795",04 May
59,Multiple carrier,BOM,LCY,BOM → CDG → AMS → LCY,02:10,16:40,19h 0m,2 stops,"₹3,65,059",04 May
60,Multiple carrier,BOM,LHR,BOM → RUH → LHR,12:30,06:205 May,22h 20m,1 stop,"₹4,10,784",04 May

In [27]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("//span[@class='bg-warning-100 br-100 fw-600 fs-2 lh-copy px-2 py-0']")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('4 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df6=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [28]:
df6['Date Of Journey'] = '05 May'
df6

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,06:256 May,16h 20m,1 stop,"₹67,909",05 May
1,Qatar Airways,BOM,LHR,BOM → DOH → LHR,18:35,14:106 May,24h 5m,1 stop,"₹68,184",05 May
2,Vistara,BOM,LHR,BOM → DEL → LHR,10:25,19:50,13h 55m,1 stop,"₹68,365",05 May
3,Air India,BOM,LHR,BOM → DEL → LHR,10:00,19:00,13h 30m,1 stop,"₹69,655",05 May
4,Multiple carrier,BOM,MAN,BOM → AUH → BRU → MAN,20:55,10:206 May,17h 55m,2 stops,"₹70,476",05 May
...,...,...,...,...,...,...,...,...,...,...
56,KLM Royal Dutch,BOM,MAN,BOM → AMS → MAN,02:25,10:25,12h 30m,1 stop,"₹4,12,428",05 May
57,Air France,BOM,MAN,BOM → CDG → MAN,02:10,21:40,24h 0m,1 stop,"₹4,12,547",05 May
58,KLM Royal Dutch,BOM,MAN,BOM → CDG → AMS → MAN,02:10,16:45,19h 5m,2 stops,"₹4,13,859",05 May
59,Multiple carrier,BOM,MAN,BOM → DXB → MAN,04:30,12:00,12h 0m,1 stop,"₹5,45,468",05 May
60,Multiple carrier,BOM,LHR,BOM → BAH → LHR,21:45,06:156 May,13h 0m,1 stop,"₹6,16,618",05 May

In [32]:
Flight=pd.concat([df,df2,df3,df4,df5,df6])
Flight

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,03:10,20:00,21h 20m,1 stop,"₹64,734",30 Apr
1,Vistara,BOM,LHR,BOM → DEL → LHR,06:30,19:50,17h 50m,1 stop,"₹68,365",30 Apr
2,Vistara,BOM,LHR,BOM → DEL → LHR,08:45,19:50,15h 35m,1 stop,"₹68,770",30 Apr
3,Air India,BOM,LHR,BOM → IDR → DEL → LHR,07:05,19:00,16h 25m,2 stops,"₹69,655",30 Apr
4,Emirates,BOM,LGW,BOM → DXB → LGW,19:20,12:35,21h 45m,1 stop,"₹71,648",30 Apr
...,...,...,...,...,...,...,...,...,...,...
56,KLM Royal Dutch,BOM,MAN,BOM → AMS → MAN,02:25,10:25,12h 30m,1 stop,"₹4,12,428",05 May
57,Air France,BOM,MAN,BOM → CDG → MAN,02:10,21:40,24h 0m,1 stop,"₹4,12,547",05 May
58,KLM Royal Dutch,BOM,MAN,BOM → CDG → AMS → MAN,02:10,16:45,19h 5m,2 stops,"₹4,13,859",05 May
59,Multiple carrier,BOM,MAN,BOM → DXB → MAN,04:30,12:00,12h 0m,1 stop,"₹5,45,468",05 May
60,Multiple carrier,BOM,LHR,BOM → BAH → LHR,21:45,06:156 May,13h 0m,1 stop,"₹6,16,618",05 May

In [33]:
# Mumbai-SanFrancisco Flight Details

In [43]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[3]/span")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('1 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df7=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [44]:
df7['Date Of Journey'] = '30 Apr'
df7

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Singapore Air,BOM,LAX,BOM → SIN → LAX → SJC,11:45,09:44,34h 29m,2 stops,"₹1,09,008",30 Apr
1,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,21:46,32h 6m,2 stops,"₹1,20,840",30 Apr
2,Multiple carrier,BOM,LAX,BOM → DXB → LAX → SFO,05:10,19:10,26h 30m,2 stops,"₹1,28,623",30 Apr
3,Multiple carrier,BOM,ORD,BOM → DEL → ORD → SJC,21:55,22:30,37h 5m,2 stops,"₹1,40,962",30 Apr
4,Lufthansa,BOM,SFO,BOM → MUC → SFO,00:50,18:55,30h 35m,1 stop,"₹1,43,778",30 Apr
...,...,...,...,...,...,...,...,...,...,...
56,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,18:10,28h 30m,2 stops,"₹6,47,526",30 Apr
57,Multiple carrier,BOM,SFO,BOM → DXB → SFO,01:05,14:00,25h 25m,1 stop,"₹6,48,569",30 Apr
58,Multiple carrier,BOM,LAX,BOM → NRT → LAX → SJC,19:40,18:09,34h 59m,2 stops,"₹7,47,242",30 Apr
59,Multiple carrier,BOM,SFO,BOM → LHR → SFO,06:30,17:05,23h 5m,1 stop,"₹12,01,399",30 Apr
60,Multiple carrier,BOM,SFO,BOM → SIN → SFO,23:50,19:05,31h 45m,1 stop,"₹12,19,429",30 Apr

In [45]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[3]/span")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('2 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df8=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [46]:
df8['Date Of Journey'] = '01 May'
df8

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Multiple carrier,BOM,SLC,BOM → CDG → SLC → SJC,02:10,23:43,34h 3m,2 stops,"₹1,20,789",01 May
1,Multiple carrier,BOM,LHR,BOM → DXB → LHR → SFO,22:20,15:35,29h 45m,2 stops,"₹1,22,522",01 May
2,Air France,BOM,LHR,BOM → CDG → LHR → SFO,02:10,15:35,25h 55m,2 stops,"₹1,23,628",01 May
3,Multiple carrier,BOM,LAX,BOM → DOH → LAX → SJC,18:35,18:52,36h 47m,2 stops,"₹1,27,567",01 May
4,Delta,BOM,SFO,BOM → CDG → SFO,02:10,13:15,23h 35m,1 stop,"₹1,43,576",01 May
...,...,...,...,...,...,...,...,...,...,...
60,Multiple carrier,BOM,SEA,BOM → DOH → SEA → SJC,04:25,18:10,26h 15m,2 stops,"₹6,40,530",01 May
61,Multiple carrier,BOM,SEA,BOM → DXB → SEA → SJC,05:10,18:10,25h 30m,2 stops,"₹6,42,739",01 May
62,Multiple carrier,BOM,SFO,BOM → DXB → SFO,01:05,14:00,25h 25m,1 stop,"₹6,48,569",01 May
63,Delta,BOM,LAX,BOM → AMS → LAX → SJC,02:20,18:09,28h 19m,2 stops,"₹6,94,473",01 May
64,Multiple carrier,BOM,LAX,BOM → AMS → LAX → SJC,02:20,18:09,28h 19m,2 stops,"₹6,95,676",01 May

In [47]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[3]/span")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('3 May',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df9=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [48]:
df9['Date Of Journey'] = '02 May'
df9

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Singapore Air,BOM,LAX,BOM → SIN → LAX → SJC,11:45,09:44,34h 29m,2 stops,"₹1,09,008",02 May
1,Emirates,BOM,SFO,BOM → DXB → SFO,19:20,14:00,31h 10m,1 stop,"₹1,12,624",02 May
2,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,04:25,23:00,31h 5m,2 stops,"₹1,24,695",02 May
3,Delta,BOM,SEA,BOM → AMS → SEA → SJC,02:25,21:46,31h 51m,2 stops,"₹1,43,770",02 May
4,Multiple carrier,BOM,SEA,BOM → AMS → SEA → SJC,02:25,20:56,31h 1m,2 stops,"₹1,44,956",02 May
5,Emirates,BOM,SFO,BOM → DXB → SFO,04:30,14:00,22h 0m,1 stop,"₹1,47,720",02 May
6,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,04:25,18:52,26h 57m,2 stops,"₹1,53,224",02 May
7,Turkish Airlines,BOM,SFO,BOM → IST → SFO,06:25,16:35,22h 40m,1 stop,"₹1,53,537",02 May
8,Qatar Airways,BOM,SFO,BOM → DOH → SFO,04:25,13:45,21h 50m,1 stop,"₹1,58,165",02 May
9,Emirates,BOM,SFO,BOM → DXB → SFO,05:10,14:00,21h 20m,1 stop,"₹1,63,811",02 May
10,Multiple carrier,BOM,SEA,BOM → DXB → SEA → SJC,05:10,18:10,25h 30m,2 stops,"₹1,63,819",02 May
11,Multiple carrier,BOM,LHR,BOM → DXB → LHR → SFO,22:20,15:35,29h 45m,2 stops,"₹1,70,943",02 May
12,Delta,BOM,SFO,BOM → AMS → SFO,02:25,11:45,21h 50m,1 stop,"₹1,76,175",02 May
13,Delta,BOM,SEA,BOM → AMS → SEA → SJC,02:25,17:29,27h 34m,2 stops,"₹1,76,262",02 May
14,Delta,BOM,LAX,BOM → AMS → LAX → SJC,02:25,18:09,28h 14m,2 stops,"₹1,76,604",02 May
15,Emirates,BOM,JFK,BOM → DXB → JFK → SFO,22:20,15:28,29h 38m,2 stops,"₹1,77,180",02 May
16,KLM Royal Dutch,BOM,SFO,BOM → AMS → SFO,02:25,11:45,21h 50m,1 stop,"₹1,77,340",02 May
17,KLM Royal Dutch,BOM,SEA,BOM → AMS → SEA → SJC,02:25,17:29,27h 34m,2 stops,"₹1,77,448",02 May
18,KLM Royal Dutch,BOM,LAX,BOM → AMS → LAX → SJC,02:25,18:09,28h 14m,2 stops,"₹1,77,769",02 May
19,KLM Royal Dutch,BOM,LHR,BOM → AMS → LHR → SFO,02:25,15:35,25h 40m,2 stops,"₹1,81,169",02 May
20,KLM Royal Dutch,BOM,LCY,BOM → AMS → LCY → LHR → SFO,02:25,15:35,25h 40m,2 stops,"₹1,82,489",02 May
21,Qatar Airways,BOM,SFO,BOM → DOH → SFO,04:55,13:45,21h 20m,1 stop,"₹2,07,237",02 May
22,Multiple carrier,BOM,SEA,BOM → DOH → SEA → SJC,04:55,22:59,30h 34m,2 stops,"₹2,09,139",02 May
23,Qatar Airways,BOM,SEA,BOM → DOH → SEA → SJC,04:55,18:10,25h 45m,2 stops,"₹2,10,023",02 May
24,Multiple carrier,BOM,LAX,BOM → DOH → LAX → SJC,04:55,18:52,26h 27m,2 stops,"₹2,26,034",02 May
25,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,04:55,23:00,30h 35m,2 stops,"₹2,26,918",02 May
26,Qatar Airways,BOM,SFO,BOM → DOH → SFO,18:35,13:45,31h 40m,1 stop,"₹2,38,943",02 May
27,Qatar Airways,BOM,SEA,BOM → DOH → SEA → SJC,18:35,18:10,36h 5m,2 stops,"₹2,41,179",02 May
28,Multiple carrier,BOM,LAX,BOM → DOH → LAX → SJC,18:35,11:01,28h 56m,2 stops,"₹2,95,523",02 May
29,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,04:55,18:55,26h 30m,2 stops,"₹2,96,407",02 May
30,Multiple carrier,BOM,ORD,BOM → DEL → ORD → SJC,21:55,22:30,37h 5m,2 stops,"₹3,47,339",02 May
31,British Airways,BOM,DUB,BOM → LHR → DUB → SFO,13:10,15:35,38h 55m,2 stops,"₹3,82,202",02 May
32,British Airways,BOM,DUB,BOM → LHR → DUB → SFO,13:10,15:35,38h 55m,2 stops,"₹3,82,716",02 May
33,British Airways,BOM,DUB,BOM → LHR → DUB → SFO,13:10,15:35,38h 55m,2 stops,"₹3,83,069",02 May
34,British Airways,BOM,LGW,BOM → LHR → LGW → DUB → SFO,13:10,15:35,38h 55m,2 stops,"₹3,83,618",02 May
35,United,BOM,ORD,BOM → DEL → ORD → SJC,19:45,22:30,39h 15m,2 stops,"₹4,10,137",02 May
36,Multiple carrier,BOM,SEA,BOM → DXB → SEA → SJC,22:20,18:10,32h 20m,2 stops,"₹4,30,107",02 May
37,Multiple carrier,BOM,LHR,BOM → DXB → LHR → SFO,20:20,14:15,30h 25m,2 stops,"₹4,40,091",02 May
38,Multiple carrier,BOM,SFO,BOM → SIN → SFO,23:50,19:05,31h 45m,1 stop,"₹4,44,056",02 May
39,Multiple carrier,BOM,LAX,BOM → MUC → LAX → SJC,00:50,18:52,30h 32m,2 stops,"₹5,18,069",02 May
40,Multiple carrier,BOM,LAX,BOM → LHR → LAX → SFO,10:15,23:41,25h 56m,2 stops,"₹5,33,924",02 May
41,Multiple carrier,BOM,ORD,BOM → DEL → ORD → SJC,20:55,22:30,38h 5m,2 stops,"₹6,01,072",02 May
42,Multiple carrier,BOM,SFO,BOM → DXB → SFO,23:05,14:00,27h 25m,1 stop,"₹6,08,396",02 May
43,Multiple carrier,BOM,SFO,BOM → DXB → SFO,01:05,14:00,25h 25m,1 stop,"₹6,48,569",02 May
44,Multiple carrier,BOM,LHR,BOM → AUH → LHR → SFO,04:35,17:05,25h 0m,2 stops,"₹10,22,719",02 May
45,Multiple carrier,BOM,LAX,BOM → LHR → LAX → SJC,10:15,11:01,37h 16m,2 stops,"₹14,05,882",02 May

In [49]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
t = []
dest= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[3]/span")
for i in dest:
    t.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('4 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df10=pd.DataFrame({'Airline Name':a,'Source':s,'Destination':t,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [50]:
df10['Date Of Journey'] = '03 May'
df10

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Singapore Air,BOM,LAX,BOM → SIN → LAX → SJC,11:45,09:444 May,34h 29m,2 stops,"₹1,09,008",03 May
1,Emirates,BOM,SFO,BOM → DXB → SFO,22:20,14:004 May,28h 10m,1 stop,"₹1,18,084",03 May
2,Singapore Air,BOM,NRT,BOM → SIN → NRT → LAX → SJC,23:40,17:064 May,29h 56m,3 stops,"₹1,27,179",03 May
3,Multiple carrier,BOM,SEA,BOM → DXB → SEA → SJC,22:20,18:104 May,32h 20m,2 stops,"₹1,34,177",03 May
4,Emirates,BOM,JFK,BOM → DXB → JFK → SJC,19:20,20:374 May,37h 47m,2 stops,"₹1,41,968",03 May
5,Lufthansa,BOM,SFO,BOM → FRA → SFO,02:50,12:40,22h 20m,1 stop,"₹1,43,137",03 May
6,Delta,BOM,SFO,BOM → CDG → SFO,02:10,13:15,23h 35m,1 stop,"₹1,43,576",03 May
7,Delta,BOM,SEA,BOM → CDG → SEA → SJC,02:10,17:29,27h 49m,2 stops,"₹1,43,810",03 May
8,Delta,BOM,LAX,BOM → CDG → LAX → SJC,02:10,09:074 May,43h 27m,2 stops,"₹1,44,005",03 May
9,Air France,BOM,SFO,BOM → CDG → SFO,02:10,13:15,23h 35m,1 stop,"₹1,44,741",03 May
10,Emirates,BOM,JFK,BOM → DXB → JFK → SJC,22:20,20:374 May,34h 47m,2 stops,"₹1,47,428",03 May
11,Emirates,BOM,SFO,BOM → DXB → SFO,19:20,14:004 May,31h 10m,1 stop,"₹1,47,720",03 May
12,Turkish Airlines,BOM,SFO,BOM → IST → SFO,06:25,16:35,22h 40m,1 stop,"₹1,52,487",03 May
13,Qatar Airways,BOM,SFO,BOM → DOH → SFO,04:55,13:45,21h 20m,1 stop,"₹1,58,165",03 May
14,Delta,BOM,SEA,BOM → CDG → SEA → SJC,02:10,21:46,32h 6m,2 stops,"₹1,65,749",03 May
15,Multiple carrier,BOM,LHR,BOM → DXB → LHR → SFO,22:20,15:354 May,29h 45m,2 stops,"₹1,70,943",03 May
16,Multiple carrier,BOM,LHR,BOM → DEL → LHR → SFO,22:45,15:354 May,29h 20m,2 stops,"₹1,74,369",03 May
17,Delta,BOM,LAX,BOM → CDG → LAX → SJC,02:10,18:09,28h 29m,2 stops,"₹1,76,497",03 May
18,Emirates,BOM,SFO,BOM → DXB → SFO,04:30,14:00,22h 0m,1 stop,"₹1,91,516",03 May
19,British Airways,BOM,LHR,BOM → DEL → LHR → SFO,20:55,14:154 May,29h 50m,2 stops,"₹1,95,702",03 May
20,Multiple carrier,BOM,SEA,BOM → DXB → SEA → SJC,04:30,18:10,26h 10m,2 stops,"₹2,07,604",03 May
21,Multiple carrier,BOM,JFK,BOM → LHR → JFK → SJC,13:10,20:374 May,43h 57m,2 stops,"₹2,17,177",03 May
22,Multiple carrier,BOM,LHR,BOM → AUH → LHR → SFO,20:55,13:354 May,29h 10m,2 stops,"₹2,20,054",03 May
23,Emirates,BOM,JFK,BOM → DXB → JFK → SJC,04:30,21:38,29h 38m,2 stops,"₹2,20,855",03 May
24,Multiple carrier,BOM,JFK,BOM → DEL → JFK → SFO,18:30,12:204 May,30h 20m,2 stops,"₹2,22,119",03 May
25,Multiple carrier,BOM,JFK,BOM → DOH → JFK → SFO,04:25,20:38,28h 43m,2 stops,"₹2,25,461",03 May
26,Delta,BOM,SEA,BOM → CDG → SEA → SJC,02:10,21:46,32h 6m,2 stops,"₹2,29,684",03 May
27,Delta,BOM,LAX,BOM → CDG → LAX → SJC,02:10,22:23,32h 43m,2 stops,"₹2,29,769",03 May
28,Multiple carrier,BOM,LAX,BOM → CDG → LAX → SJC,02:10,22:23,32h 43m,2 stops,"₹2,30,954",03 May
29,Qatar Airways,BOM,SFO,BOM → DOH → SFO,18:35,13:454 May,31h 40m,1 stop,"₹2,38,943",03 May
30,Qatar Airways,BOM,SEA,BOM → DOH → SEA → SJC,04:55,18:10,25h 45m,2 stops,"₹2,40,904",03 May
31,Qatar Airways,BOM,SEA,BOM → DOH → SEA → SJC,18:35,18:104 May,36h 5m,2 stops,"₹2,41,179",03 May
32,Multiple carrier,BOM,DFW,BOM → DOH → DFW → SJC,04:55,21:08,28h 43m,2 stops,"₹2,42,335",03 May
33,Qatar Airways,BOM,DFW,BOM → DOH → DFW → SJC,04:25,21:08,29h 13m,2 stops,"₹2,43,219",03 May
34,Multiple carrier,BOM,LHR,BOM → AUH → LHR → SFO,20:55,14:154 May,29h 50m,2 stops,"₹2,64,924",03 May
35,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,18:35,18:554 May,36h 50m,2 stops,"₹2,96,682",03 May
36,Multiple carrier,BOM,DFW,BOM → DOH → DFW → SJC,18:35,21:084 May,39h 3m,2 stops,"₹3,08,622",03 May
37,Multiple carrier,BOM,DFW,BOM → DOH → DFW → SJC,18:35,21:084 May,39h 3m,2 stops,"₹3,08,897",03 May
38,Air India,BOM,DEL,BOM → CCU → DEL → SFO,21:05,07:005 May,46h 25m,2 stops,"₹3,46,827",03 May
39,British Airways,BOM,DUB,BOM → LHR → DUB → SFO,13:10,15:354 May,38h 55m,2 stops,"₹3,82,202",03 May
40,British Airways,BOM,DUB,BOM → LHR → DUB → SFO,13:10,15:354 May,38h 55m,2 stops,"₹3,82,716",03 May
41,British Airways,BOM,DUB,BOM → LHR → DUB → SFO,13:10,15:354 May,38h 55m,2 stops,"₹3,83,069",03 May
42,British Airways,BOM,LGW,BOM → LHR → LGW → DUB → SFO,13:10,15:354 May,38h 55m,2 stops,"₹3,83,618",03 May
43,Multiple carrier,BOM,LHR,BOM → DXB → LHR → SFO,20:20,14:154 May,30h 25m,2 stops,"₹4,40,091",03 May
44,Multiple carrier,BOM,ORD,BOM → AUH → ORD → SJC,04:35,22:30,30h 25m,2 stops,"₹4,69,636",03 May
45,Multiple carrier,BOM,SFO,BOM → DXB → SFO,23:05,14:004 May,27h 25m,1 stop,"₹6,08,396",03 May
46,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,04:25,18:55,27h 0m,2 stops,"₹6,21,445",03 May
47,Multiple carrier,BOM,SFO,BOM → DXB → SFO,01:05,14:00,25h 25m,1 stop,"₹6,48,569",03 May
48,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,18:10,28h 30m,2 stops,"₹6,96,948",03 May
49,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,18:10,28h 30m,2 stops,"₹6,97,289",03 May

In [51]:
Flight1=pd.concat([df7,df8,df9,df10])
Flight1

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Singapore Air,BOM,LAX,BOM → SIN → LAX → SJC,11:45,09:44,34h 29m,2 stops,"₹1,09,008",30 Apr
1,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,21:46,32h 6m,2 stops,"₹1,20,840",30 Apr
2,Multiple carrier,BOM,LAX,BOM → DXB → LAX → SFO,05:10,19:10,26h 30m,2 stops,"₹1,28,623",30 Apr
3,Multiple carrier,BOM,ORD,BOM → DEL → ORD → SJC,21:55,22:30,37h 5m,2 stops,"₹1,40,962",30 Apr
4,Lufthansa,BOM,SFO,BOM → MUC → SFO,00:50,18:55,30h 35m,1 stop,"₹1,43,778",30 Apr
...,...,...,...,...,...,...,...,...,...,...
45,Multiple carrier,BOM,SFO,BOM → DXB → SFO,23:05,14:004 May,27h 25m,1 stop,"₹6,08,396",03 May
46,Qatar Airways,BOM,LAX,BOM → DOH → LAX → SJC,04:25,18:55,27h 0m,2 stops,"₹6,21,445",03 May
47,Multiple carrier,BOM,SFO,BOM → DXB → SFO,01:05,14:00,25h 25m,1 stop,"₹6,48,569",03 May
48,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,18:10,28h 30m,2 stops,"₹6,96,948",03 May
49,Multiple carrier,BOM,SEA,BOM → CDG → SEA → SJC,02:10,18:10,28h 30m,2 stops,"₹6,97,289",03 May

In [65]:
# Goa-Dubai Flight Details

In [120]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('1 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df11=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [121]:
df11['Date Of Journey'] = '30 Apr'
df11

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,Oman Av (SAOG),GOI,GOI → MCT → DXB,21:00,09:501 May,14h 20m,1 stop,"₹11,632",30 Apr
1,Air India,BLR,BLR → GOI → DXB,17:00,22:00,6h 30m,1 stop,"₹13,210",30 Apr
2,SriLankan Airlines,BLR,BLR → CMB → DXB,03:30,21:40,19h 40m,1 stop,"₹13,420",30 Apr
3,Air India,GOI,GOI → DXB,20:00,22:00,3h 30m,non-stop,"₹13,557",30 Apr
4,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹13,803",30 Apr
5,IndiGo,GOI,GOI → BOM → AUH,18:40,23:25,6h 15m,1 stop,"₹14,444",30 Apr
6,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹14,733",30 Apr
7,IndiGo,GOI,GOI → BOM → DXB,18:40,04:001 May,10h 50m,1 stop,"₹14,864",30 Apr
8,SpiceJet,GOI,GOI → BOM → DXB,13:30,00:401 May,12h 40m,1 stop,"₹15,348",30 Apr
9,IndiGo,GOI,GOI → BOM → DXB,13:10,21:00,9h 20m,1 stop,"₹16,439",30 Apr
10,Vistara,BLR,BLR → BOM → DXB,09:30,18:15,10h 15m,1 stop,"₹17,106",30 Apr
11,IndiGo,GOI,GOI → BOM → DXB,06:45,16:55,11h 40m,1 stop,"₹17,174",30 Apr
12,IndiGo,GOI,GOI → HYD → SHJ,22:00,21:551 May,25h 25m,1 stop,"₹17,321",30 Apr
13,SpiceJet,GOI,GOI → DEL → DXB,18:10,10:101 May,17h 30m,1 stop,"₹17,551",30 Apr
14,IndiGo,GOI,GOI → HYD → SHJ,15:15,21:55,8h 10m,1 stop,"₹17,846",30 Apr
15,Emirates,BLR,BLR → DXB,10:35,12:45,3h 40m,non-stop,"₹18,282",30 Apr
16,IndiGo,GOI,GOI → BOM → DXB,00:10,10:25,11h 45m,1 stop,"₹18,854",30 Apr
17,IndiGo,GOI,GOI → HYD → DXB,02:05,09:10,8h 35m,1 stop,"₹19,841",30 Apr
18,Oman Av (SAOG),BLR,BLR → MCT → DXB,15:40,21:25,7h 15m,1 stop,"₹20,019",30 Apr
19,IndiGo,GOI,GOI → HYD → DXB,22:00,09:101 May,12h 40m,1 stop,"₹20,786",30 Apr
20,IndiGo,GOI,GOI → DEL → AUH,15:25,23:40,9h 45m,1 stop,"₹20,891",30 Apr
21,IndiGo,GOI,GOI → LKO → DXB,18:30,04:151 May,11h 15m,1 stop,"₹21,311",30 Apr
22,IndiGo,GOI,GOI → AMD → DXB,20:15,03:251 May,8h 40m,1 stop,"₹21,626",30 Apr
23,Air India,GOI,GOI → BOM → DEL → DXB,06:50,18:55,13h 35m,2 stops,"₹23,186",30 Apr
24,Air India,GOI,GOI → BOM → DEL → DXB,15:15,19:001 May,29h 15m,2 stops,"₹23,396",30 Apr
25,Multiple carrier,GOI,GOI → BOM → DXB,13:20,21:00,9h 10m,1 stop,"₹26,861",30 Apr
26,Etihad Airways,BLR,BLR → AUH → XNB,04:40,10:20,7h 10m,1 stop,"₹28,775",30 Apr
27,Air India,GOI,GOI → BOM → DXB,15:15,02:401 May,12h 55m,1 stop,"₹31,586",30 Apr
28,Air India,GOI,GOI → DEL → BOM → DXB,01:15,02:401 May,26h 55m,2 stops,"₹31,901",30 Apr
29,Air India,GOI,GOI → DEL → BOM → DXB,14:15,02:401 May,13h 55m,2 stops,"₹32,111",30 Apr
30,Air India,GOI,GOI → BOM → DXB,15:15,21:55,8h 10m,1 stop,"₹33,686",30 Apr
31,Multiple carrier,BLR,BLR → BOM → DXB,09:30,17:20,9h 20m,1 stop,"₹34,431",30 Apr
32,Ethiopian Air,BLR,BLR → ADD → DXB,02:30,15:45,14h 45m,1 stop,"₹38,771",30 Apr
33,Emirates,BLR,BLR → DXB,04:30,06:50,3h 50m,non-stop,"₹40,631",30 Apr
34,Multiple carrier,GOI,GOI → BOM → AUH → XNB,13:20,02:151 May,14h 25m,2 stops,"₹40,730",30 Apr
35,Air India,GOI,GOI → DEL → DXB,14:15,22:45,10h 0m,1 stop,"₹46,758",30 Apr
36,Multiple carrier,GOI,GOI → DEL → AUH → XNB,21:55,10:201 May,13h 55m,2 stops,"₹47,072",30 Apr
37,Air India,GOI,GOI → DEL → DXB,01:15,14:00,14h 15m,1 stop,"₹48,858",30 Apr
38,Qatar Airways,GOI,GOI → DOH → DXB,03:40,20:55,18h 45m,1 stop,"₹49,968",30 Apr
39,Emirates,BLR,BLR → DXB → ZVJ,17:10,05:151 May,13h 35m,1 stop,"₹62,921",30 Apr
40,Emirates,BLR,BLR → DXB → ZVJ,20:50,05:151 May,9h 55m,1 stop,"₹78,620",30 Apr
41,Multiple carrier,BLR,BLR → MAA → DXB,06:05,12:25,7h 50m,1 stop,"₹84,327",30 Apr
42,Multiple carrier,GOI,GOI → BOM → DXB,17:35,00:051 May,8h 0m,1 stop,"₹84,632",30 Apr
43,Multiple carrier,GOI,GOI → BOM → DXB → ZVJ,13:20,05:151 May,17h 25m,2 stops,"₹84,632",30 Apr
44,Multiple carrier,GOI,GOI → DEL → AUH → XNB,14:25,02:151 May,13h 20m,2 stops,"₹85,801",30 Apr
45,Multiple carrier,BLR,BLR → BOM → DXB,21:40,06:001 May,9h 50m,1 stop,"₹87,519",30 Apr
46,Singapore Air,BLR,BLR → SIN → DXB,23:05,18:251 May,20h 50m,1 stop,"₹89,571",30 Apr
47,Multiple carrier,BLR,BLR → BOM → DXB → ZVJ,21:40,12:151 May,16h 5m,2 stops,"₹90,564",30 Apr
48,Multiple carrier,GOI,GOI → BLR → DXB,22:50,06:501 May,9h 30m,1 stop,"₹91,997",30 Apr
49,Qatar Airways,BLR,BLR → DOH → DXB,03:55,20:55,18h 30m,1 stop,"₹94,067",30 Apr
50,Multiple carrier,BLR,BLR → MAA → DXB → ZVJ,06:05,01:151 May,20h 40m,2 stops,"₹1,27,428",30 Apr
51,Multiple carrier,GOI,GOI → BLR → AUH → XNB,14:40,10:201 May,21h 10m,2 stops,"₹1,41,497",30 Apr
52,Multiple carrier,BLR,BLR → DEL → DXB,09:45,18:10,9h 55m,1 stop,"₹1,83,310",30 Apr
53,Lufthansa,BLR,BLR → FRA → DXB,03:05,22:35,21h 0m,1 stop,"₹4,02,786",30 Apr
54,Multiple carrier,BLR,BLR → FRA → DXB,03:05,23:35,22h 0m,1 stop,"₹7,34,504",30 Apr

In [122]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('2 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df12=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [123]:
df12['Date Of Journey'] = '01 May'
df12

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,GOI,GOI → BOM → AUH,06:45,23:25,18h 10m,1 stop,"₹13,394",01 May
1,Air India,GOI,GOI → DXB,20:00,22:00,3h 30m,non-stop,"₹13,557",01 May
2,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹14,867",01 May
3,IndiGo,GOI,GOI → BOM → AUH,13:10,23:25,11h 45m,1 stop,"₹15,284",01 May
4,IndiGo,GOI,GOI → BLR → DXB,02:25,10:50,9h 55m,1 stop,"₹15,641",01 May
5,IndiGo,GOI,GOI → BOM → AUH,16:30,23:25,8h 25m,1 stop,"₹15,704",01 May
6,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹15,797",01 May
7,IndiGo,GOI,GOI → ATQ → SHJ,23:05,14:452 May,17h 10m,1 stop,"₹15,904",01 May
8,Vistara,GOI,GOI → BOM → DXB,08:40,18:15,11h 5m,1 stop,"₹15,920",01 May
9,IndiGo,GOI,GOI → BOM → DXB,00:10,10:25,11h 45m,1 stop,"₹16,439",01 May
10,SpiceJet,GOI,GOI → BOM → DXB,13:30,00:402 May,12h 40m,1 stop,"₹17,226",01 May
11,IndiGo,GOI,GOI → HYD → SHJ,07:20,21:55,16h 5m,1 stop,"₹17,269",01 May
12,IndiGo,GOI,GOI → BOM → DXB,13:10,21:00,9h 20m,1 stop,"₹17,279",01 May
13,IndiGo,GOI,GOI → BOM → DXB,06:45,16:55,11h 40m,1 stop,"₹17,909",01 May
14,Emirates,BLR,BLR → DXB → ZVJ,10:35,17:15,8h 10m,1 stop,"₹18,282",01 May
15,SpiceJet,GOI,GOI → DEL → DXB,15:05,10:102 May,20h 35m,1 stop,"₹18,371",01 May
16,IndiGo,GOI,GOI → HYD → SHJ,22:00,21:552 May,25h 25m,1 stop,"₹18,371",01 May
17,IndiGo,GOI,GOI → BOM → AUH,18:40,23:25,6h 15m,1 stop,"₹18,434",01 May
18,IndiGo,GOI,GOI → DEL → DXB,00:50,09:40,10h 20m,1 stop,"₹18,949",01 May
19,SpiceJet,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹19,093",01 May
20,SpiceJet,GOI,GOI → DEL → DXB,18:10,10:102 May,17h 30m,1 stop,"₹19,157",01 May
21,IndiGo,GOI,GOI → HYD → SHJ,14:30,21:55,8h 55m,1 stop,"₹19,631",01 May
22,IndiGo,GOI,GOI → HYD → DXB,02:05,09:10,8h 35m,1 stop,"₹20,734",01 May
23,IndiGo,GOI,GOI → DEL → AUH,15:25,23:40,9h 45m,1 stop,"₹20,839",01 May
24,IndiGo,GOI,GOI → LKO → DXB,18:30,04:152 May,11h 15m,1 stop,"₹20,996",01 May
25,IndiGo,GOI,GOI → DEL → AUH,13:55,23:40,11h 15m,1 stop,"₹21,154",01 May
26,Emirates,BLR,BLR → DXB → ZVJ,04:30,12:15,9h 15m,1 stop,"₹21,663",01 May
27,IndiGo,GOI,GOI → HYD → SHJ,15:15,21:55,8h 10m,1 stop,"₹23,070",01 May
28,Air India,GOI,GOI → BOM → DEL → DXB,06:50,19:00,13h 40m,2 stops,"₹23,186",01 May
29,IndiGo,GOI,GOI → AMD → DXB,20:15,03:252 May,8h 40m,1 stop,"₹23,411",01 May
30,IndiGo,GOI,GOI → IXC → DXB,11:40,19:50,9h 40m,1 stop,"₹25,984",01 May
31,Etihad Airways,BLR,BLR → AUH,04:40,07:05,3h 55m,non-stop,"₹28,775",01 May
32,Air India,GOI,GOI → BOM → DXB,15:15,21:55,8h 10m,1 stop,"₹31,586",01 May
33,Air India,GOI,GOI → DEL → BOM → DXB,14:15,02:402 May,13h 55m,2 stops,"₹32,111",01 May
34,Multiple carrier,GOI,GOI → BOM → DXB,08:40,17:20,10h 10m,1 stop,"₹34,016",01 May
35,Multiple carrier,GOI,GOI → DEL → AUH,21:55,07:002 May,10h 35m,1 stop,"₹40,730",01 May
36,Air India,GOI,GOI → DEL → DXB,14:15,22:45,10h 0m,1 stop,"₹46,758",01 May
37,Multiple carrier,GOI,GOI → DEL → AUH,14:25,07:002 May,18h 5m,1 stop,"₹47,072",01 May
38,Qatar Airways,GOI,GOI → DOH → SHJ,03:40,09:50,7h 40m,1 stop,"₹49,693",01 May
39,Qatar Airways,GOI,GOI → DOH → DXB,03:40,20:55,18h 45m,1 stop,"₹49,968",01 May
40,Emirates,BLR,BLR → DXB → ZVJ,20:50,05:152 May,9h 55m,1 stop,"₹62,921",01 May
41,Multiple carrier,BLR,BLR → BOM → DXB → ZVJ,21:40,12:152 May,16h 5m,2 stops,"₹66,156",01 May
42,Multiple carrier,GOI,GOI → DOH → MCT → DXB,03:40,15:40,13h 30m,2 stops,"₹67,584",01 May
43,Multiple carrier,GOI,GOI → BOM → DXB,03:45,11:40,9h 25m,1 stop,"₹74,538",01 May
44,Qatar Airways,BLR,BLR → DOH → SHJ,03:55,09:50,7h 25m,1 stop,"₹80,184",01 May
45,Multiple carrier,BLR,BLR → CMB → DOH → SHJ,21:10,09:502 May,14h 10m,2 stops,"₹81,775",01 May
46,Multiple carrier,GOI,GOI → BOM → DXB,03:45,17:20,15h 5m,1 stop,"₹84,632",01 May
47,Multiple carrier,BLR,BLR → MAA → DXB → ZVJ,06:05,17:15,12h 40m,2 stops,"₹85,982",01 May
48,Multiple carrier,GOI,GOI → DXB → XNB → AUH,20:00,04:052 May,9h 35m,1 stop,"₹86,956",01 May
49,Multiple carrier,BLR,BLR → GOI → DXB → XNB → AUH,17:00,04:052 May,12h 35m,2 stops,"₹87,659",01 May
50,Qatar Airways,BLR,BLR → DOH → SHJ,03:55,16:35,14h 10m,1 stop,"₹93,792",01 May
51,Qatar Airways,BLR,BLR → DOH → AUH,03:55,21:25,19h 0m,1 stop,"₹94,067",01 May
52,Multiple carrier,BLR,BLR → BOM → AUH,21:40,06:052 May,9h 55m,1 stop,"₹1,30,887",01 May
53,Multiple carrier,GOI,GOI → BLR → AUH,14:40,07:052 May,17h 55m,1 stop,"₹1,40,561",01 May
54,Multiple carrier,BLR,BLR → DEL → AUH,21:15,07:002 May,11h 15m,1 stop,"₹1,46,288",01 May
55,Multiple carrier,BLR,BLR → LHR → AUH,06:50,00:352 May,19h 15m,1 stop,"₹3,50,491",01 May
56,Lufthansa,BLR,BLR → FRA → AUH,03:05,19:20,17h 45m,1 stop,"₹4,41,290",01 May

In [124]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('3 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df13=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [125]:
df13['Date Of Journey'] = '02 May'
df13

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,GOI,GOI → BOM → AUH,18:40,23:25,6h 15m,1 stop,"₹13,394",02 May
1,SpiceJet,GOI,GOI → BOM → DXB,03:45,00:403 May,22h 25m,1 stop,"₹13,552",02 May
2,IndiGo,GOI,GOI → BOM → DXB,18:40,04:003 May,10h 50m,1 stop,"₹13,709",02 May
3,SpiceJet,GOI,GOI → BOM → DXB,13:30,00:403 May,12h 40m,1 stop,"₹14,286",02 May
4,IndiGo,GOI,GOI → BOM → DXB,06:45,16:55,11h 40m,1 stop,"₹15,389",02 May
5,IndiGo,GOI,GOI → ATQ → SHJ,23:05,14:453 May,17h 10m,1 stop,"₹15,589",02 May
6,IndiGo,GOI,GOI → BLR → DXB,02:25,10:50,9h 55m,1 stop,"₹15,641",02 May
7,IndiGo,GOI,GOI → BOM → DXB,13:10,21:00,9h 20m,1 stop,"₹15,914",02 May
8,IndiGo,GOI,GOI → HYD → SHJ,07:20,21:55,16h 5m,1 stop,"₹17,269",02 May
9,IndiGo,GOI,GOI → DEL → DXB,00:50,09:40,10h 20m,1 stop,"₹17,857",02 May
10,SpiceJet,GOI,GOI → DEL → DXB,18:10,10:103 May,17h 30m,1 stop,"₹18,371",02 May
11,IndiGo,GOI,GOI → HYD → SHJ,15:15,21:55,8h 10m,1 stop,"₹18,686",02 May
12,IndiGo,GOI,GOI → LKO → DXB,18:30,04:153 May,11h 15m,1 stop,"₹19,001",02 May
13,SpiceJet,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹19,093",02 May
14,IndiGo,GOI,GOI → AMD → DXB,20:15,03:253 May,8h 40m,1 stop,"₹19,474",02 May
15,IndiGo,GOI,GOI → HYD → SHJ,14:30,21:55,8h 55m,1 stop,"₹19,631",02 May
16,IndiGo,GOI,GOI → HYD → DXB,02:05,09:10,8h 35m,1 stop,"₹19,789",02 May
17,IndiGo,GOI,GOI → DEL → AUH,15:25,23:40,9h 45m,1 stop,"₹20,839",02 May
18,Air India,GOI,GOI → BOM → DEL → DXB,06:50,19:00,13h 40m,2 stops,"₹23,186",02 May
19,Air India,GOI,GOI → BOM → DEL → DXB,23:10,19:003 May,21h 20m,2 stops,"₹25,286",02 May
20,Multiple carrier,GOI,GOI → BOM → DXB,13:20,21:00,9h 10m,1 stop,"₹27,333",02 May
21,Multiple carrier,GOI,GOI → BOM → BAH → DXB,13:20,04:153 May,16h 25m,2 stops,"₹29,171",02 May
22,Air India,GOI,GOI → BOM → DXB,15:15,21:55,8h 10m,1 stop,"₹31,586",02 May
23,Air India,GOI,GOI → DEL → BOM → DXB,14:15,02:403 May,13h 55m,2 stops,"₹31,901",02 May
24,Oman Av (SAOG),GOI,GOI → MCT → DXB,04:55,09:50,6h 25m,1 stop,"₹32,699",02 May
25,Oman Av (SAOG),GOI,GOI → MCT → DXB,04:55,15:40,12h 15m,1 stop,"₹35,800",02 May
26,Multiple carrier,GOI,GOI → BOM → BAH → AUH,13:20,03:553 May,16h 5m,2 stops,"₹36,669",02 May
27,Multiple carrier,GOI,GOI → DEL → AUH,21:55,07:003 May,10h 35m,1 stop,"₹37,107",02 May
28,Multiple carrier,GOI,GOI → DEL → DXB,21:55,13:003 May,16h 35m,1 stop,"₹43,010",02 May
29,Qatar Airways,GOI,GOI → DOH → SHJ,03:40,09:50,7h 40m,1 stop,"₹43,335",02 May
30,Air India,GOI,GOI → DEL → DXB,14:15,22:45,10h 0m,1 stop,"₹46,758",02 May
31,Qatar Airways,GOI,GOI → DOH → DXB,03:40,20:55,18h 45m,1 stop,"₹48,340",02 May
32,Multiple carrier,GOI,GOI → BOM → DXB,03:45,11:40,9h 25m,1 stop,"₹59,069",02 May
33,Multiple carrier,GOI,GOI → BLR → DXB,22:50,06:503 May,9h 30m,1 stop,"₹64,441",02 May
34,Multiple carrier,GOI,GOI → DEL → DXB,15:05,23:55,10h 20m,1 stop,"₹70,859",02 May
35,Multiple carrier,GOI,GOI → HYD → DXB,21:05,12:103 May,16h 35m,1 stop,"₹73,217",02 May
36,Multiple carrier,GOI,GOI → BLR → DXB → ZVJ,22:50,12:153 May,14h 55m,2 stops,"₹75,613",02 May
37,Multiple carrier,GOI,GOI → BOM → DXB,13:20,06:003 May,18h 10m,1 stop,"₹83,477",02 May
38,Multiple carrier,GOI,GOI → DEL → DXB,21:55,06:203 May,9h 55m,1 stop,"₹85,550",02 May
39,Multiple carrier,GOI,GOI → DEL → DXB,18:10,06:203 May,13h 40m,1 stop,"₹85,550",02 May
40,Multiple carrier,GOI,GOI → HYD → DXB,21:05,06:403 May,11h 5m,1 stop,"₹88,123",02 May
41,Multiple carrier,GOI,GOI → BLR → AUH,14:40,07:053 May,17h 55m,1 stop,"₹1,40,561",02 May
42,Multiple carrier,GOI,GOI → BLR → AUH → XNB,14:40,02:153 May,13h 5m,2 stops,"₹1,41,497",02 May
43,Multiple carrier,GOI,GOI → DEL → AUH,14:25,23:20,10h 25m,1 stop,"₹1,67,156",02 May
44,Multiple carrier,GOI,GOI → BLR → AUH,14:40,23:20,10h 10m,1 stop,"₹2,68,580",02 May

In [126]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('4 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df14=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [127]:
df14['Date Of Journey'] = '03 May'
df14

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,GOI,GOI → BOM → AUH,06:45,23:25,18h 10m,1 stop,"₹13,394",03 May
1,GO FIRST,GOI,GOI → BOM → AUH,06:40,22:10,17h 0m,1 stop,"₹13,757",03 May
2,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹13,803",03 May
3,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹14,733",03 May
4,IndiGo,GOI,GOI → BOM → DXB,00:10,10:25,11h 45m,1 stop,"₹15,389",03 May
...,...,...,...,...,...,...,...,...,...
57,Qatar Airways,BLR,BLR → DOH → SHJ,03:55,09:50,7h 25m,1 stop,"₹1,53,413",03 May
58,Multiple carrier,BLR,BLR → HYD → AUH,20:10,07:004 May,12h 20m,1 stop,"₹2,49,979",03 May
59,Multiple carrier,GOI,GOI → LHR → AUH,04:35,00:354 May,21h 30m,1 stop,"₹3,31,244",03 May
60,Multiple carrier,BLR,BLR → LHR → AUH,06:50,00:354 May,19h 15m,1 stop,"₹3,50,491",03 May
61,Lufthansa,BLR,BLR → FRA → AUH,03:05,19:20,17h 45m,1 stop,"₹4,67,678",03 May

In [128]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('5 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df15=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [129]:
df15['Date Of Journey'] = '04 May'
df15

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,GOI,GOI → BOM → AUH,06:45,23:25,18h 10m,1 stop,"₹16,271",04 May
1,IndiGo,GOI,GOI → BOM → AUH,00:10,23:25,24h 45m,1 stop,"₹16,691",04 May
2,IndiGo,GOI,GOI → BOM → AUH,18:40,23:25,6h 15m,1 stop,"₹18,686",04 May
3,IndiGo,GOI,GOI → BOM → DXB,06:45,16:55,11h 40m,1 stop,"₹18,749",04 May
4,IndiGo,GOI,GOI → BOM → AUH,13:10,23:25,11h 45m,1 stop,"₹19,001",04 May
5,IndiGo,GOI,GOI → BOM → DXB,00:10,10:25,11h 45m,1 stop,"₹19,169",04 May
6,IndiGo,GOI,GOI → ATQ → SHJ,23:05,14:455 May,17h 10m,1 stop,"₹19,243",04 May
7,IndiGo,GOI,GOI → DEL → AUH,15:25,23:40,9h 45m,1 stop,"₹20,839",04 May
8,IndiGo,GOI,GOI → HYD → SHJ,07:20,21:55,16h 5m,1 stop,"₹20,891",04 May
9,SpiceJet,GOI,GOI → BOM → DXB,13:30,00:405 May,12h 40m,1 stop,"₹21,112",04 May
10,IndiGo,GOI,GOI → BOM → DXB,18:40,04:005 May,10h 50m,1 stop,"₹21,710",04 May
11,IndiGo,GOI,GOI → DEL → AUH,13:00,23:40,12h 10m,1 stop,"₹21,784",04 May
12,IndiGo,GOI,GOI → DEL → AUH,22:00,23:405 May,27h 10m,1 stop,"₹21,973",04 May
13,IndiGo,GOI,GOI → HYD → DXB,02:05,09:10,8h 35m,1 stop,"₹22,781",04 May
14,IndiGo,GOI,GOI → HYD → SHJ,14:30,21:55,8h 55m,1 stop,"₹23,096",04 May
15,IndiGo,GOI,GOI → DEL → DXB,22:00,09:405 May,13h 10m,1 stop,"₹23,233",04 May
16,IndiGo,GOI,GOI → BOM → DXB,13:10,21:00,9h 20m,1 stop,"₹23,369",04 May
17,IndiGo,GOI,GOI → AMD → DXB,20:15,03:255 May,8h 40m,1 stop,"₹23,863",04 May
18,IndiGo,GOI,GOI → HYD → SHJ,15:15,21:55,8h 10m,1 stop,"₹24,041",04 May
19,IndiGo,GOI,GOI → LKO → DXB,18:30,04:155 May,11h 15m,1 stop,"₹24,335",04 May
20,SpiceJet,GOI,GOI → DEL → DXB,18:10,10:105 May,17h 30m,1 stop,"₹24,355",04 May
21,SpiceJet,GOI,GOI → DEL → DXB,15:05,10:105 May,20h 35m,1 stop,"₹25,143",04 May
22,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹25,691",04 May
23,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹26,621",04 May
24,SpiceJet,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹27,204",04 May
25,Air India,GOI,GOI → BOM → MAA → DXB,23:10,21:305 May,23h 50m,2 stops,"₹28,436",04 May
26,Air India,GOI,GOI → BOM → DEL → DXB,23:10,19:005 May,21h 20m,2 stops,"₹29,486",04 May
27,Air India,GOI,GOI → DEL → IXU → BOM → DXB,14:15,10:005 May,21h 15m,3 stops,"₹31,901",04 May
28,Oman Av (SAOG),GOI,GOI → MCT → DXB,04:55,09:50,6h 25m,1 stop,"₹35,800",04 May
29,Multiple carrier,GOI,GOI → BOM → BAH → DXB,13:20,04:155 May,16h 25m,2 stops,"₹36,206",04 May
30,Multiple carrier,GOI,GOI → BOM → BAH → AUH,13:20,03:555 May,16h 5m,2 stops,"₹36,669",04 May
31,Multiple carrier,GOI,GOI → BOM → AUH,13:20,22:25,10h 35m,1 stop,"₹37,107",04 May
32,Air India,GOI,GOI → BOM → DXB,23:10,10:005 May,12h 20m,1 stop,"₹37,886",04 May
33,Air India,GOI,GOI → BOM → DXB,15:15,21:55,8h 10m,1 stop,"₹43,136",04 May
34,Oman Av (SAOG),GOI,GOI → MCT → DXB,04:55,15:40,12h 15m,1 stop,"₹43,378",04 May
35,Hahn Air,GOI,GOI → BOM → DXB,17:35,00:405 May,8h 35m,1 stop,"₹44,473",04 May
36,Hahn Air,GOI,GOI → BOM → DXB,13:30,00:405 May,12h 40m,1 stop,"₹45,313",04 May
37,Hahn Air,GOI,GOI → DEL → DXB,23:00,10:105 May,12h 40m,1 stop,"₹45,670",04 May
38,Hahn Air,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹50,017",04 May
39,Air India,GOI,GOI → DEL → DXB,14:15,22:45,10h 0m,1 stop,"₹53,058",04 May
40,Multiple carrier,GOI,GOI → BOM → DXB,13:20,21:00,9h 10m,1 stop,"₹59,069",04 May
41,Hahn Air,GOI,GOI → BOM → DEL → DXB,03:45,18:25,16h 10m,2 stops,"₹60,737",04 May
42,Multiple carrier,GOI,GOI → BLR → DXB,22:50,06:505 May,9h 30m,1 stop,"₹64,441",04 May
43,Hahn Air,GOI,GOI → DEL → BOM → DXB,15:05,00:405 May,11h 5m,2 stops,"₹65,525",04 May
44,Multiple carrier,GOI,GOI → DEL → DXB,14:25,23:55,11h 0m,1 stop,"₹70,859",04 May
45,Multiple carrier,GOI,GOI → BLR → DXB → ZVJ,22:50,12:155 May,14h 55m,2 stops,"₹75,613",04 May
46,Multiple carrier,GOI,GOI → BOM → DXB,03:45,11:40,9h 25m,1 stop,"₹83,477",04 May
47,Multiple carrier,GOI,GOI → BOM → DXB → ZVJ,13:20,05:155 May,17h 25m,2 stops,"₹83,477",04 May
48,Multiple carrier,GOI,GOI → DEL → DXB,21:55,06:205 May,9h 55m,1 stop,"₹85,550",04 May
49,Multiple carrier,GOI,GOI → DEL → DXB,18:10,06:205 May,13h 40m,1 stop,"₹85,550",04 May
50,Qatar Airways,GOI,GOI → DOH → SHJ,03:40,09:50,7h 40m,1 stop,"₹86,711",04 May
51,Multiple carrier,GOI,GOI → DEL → BAH → DXB,14:25,04:155 May,15h 20m,2 stops,"₹86,789",04 May
52,Qatar Airways,GOI,GOI → DOH → DXB,03:40,21:30,19h 20m,1 stop,"₹86,986",04 May
53,Multiple carrier,GOI,GOI → BLR → AUH,14:40,23:20,10h 10m,1 stop,"₹1,40,561",04 May
54,Multiple carrier,GOI,GOI → BLR → AUH → XNB,14:40,02:155 May,13h 5m,2 stops,"₹1,41,497",04 May
55,Qatar Airways,GOI,GOI → DOH → DXB,03:40,20:55,18h 45m,1 stop,"₹1,58,809",04 May
56,Multiple carrier,GOI,GOI → DEL → AUH,14:25,23:20,10h 25m,1 stop,"₹1,67,156",04 May
57,Multiple carrier,GOI,GOI → DEL → DOH → SHJ,21:55,16:355 May,20h 10m,2 stops,"₹2,05,731",04 May

In [130]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('6 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df16=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [131]:
df16['Date Of Journey'] = '05 May'
df16

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,GOI,GOI → BOM → AUH,06:45,23:25,18h 10m,1 stop,"₹18,455",05 May
1,IndiGo,GOI,GOI → BOM → AUH,18:40,23:25,6h 15m,1 stop,"₹19,085",05 May
2,IndiGo,GOI,GOI → BOM → DXB,06:45,16:55,11h 40m,1 stop,"₹19,190",05 May
3,IndiGo,GOI,GOI → ATQ → SHJ,23:05,14:456 May,17h 10m,1 stop,"₹19,243",05 May
4,IndiGo,GOI,GOI → BOM → DXB,18:40,04:006 May,10h 50m,1 stop,"₹19,400",05 May
5,IndiGo,GOI,GOI → HYD → SHJ,07:20,21:55,16h 5m,1 stop,"₹19,663",05 May
6,IndiGo,GOI,GOI → BOM → AUH,16:30,23:25,8h 25m,1 stop,"₹19,715",05 May
7,IndiGo,GOI,GOI → HYD → DXB,02:05,09:10,8h 35m,1 stop,"₹20,188",05 May
8,IndiGo,GOI,GOI → BLR → DXB,02:25,10:50,9h 55m,1 stop,"₹20,240",05 May
9,IndiGo,GOI,GOI → HYD → SHJ,22:00,21:556 May,25h 25m,1 stop,"₹20,713",05 May
10,IndiGo,GOI,GOI → BOM → DXB,00:10,10:25,11h 45m,1 stop,"₹21,500",05 May
11,SpiceJet,GOI,GOI → BOM → DXB,13:30,00:406 May,12h 40m,1 stop,"₹21,952",05 May
12,IndiGo,GOI,GOI → DEL → AUH,15:25,23:40,9h 45m,1 stop,"₹21,973",05 May
13,IndiGo,GOI,GOI → HYD → SHJ,14:30,21:55,8h 55m,1 stop,"₹22,025",05 May
14,IndiGo,GOI,GOI → HYD → DXB,22:00,09:106 May,12h 40m,1 stop,"₹22,708",05 May
15,IndiGo,GOI,GOI → BOM → DXB,13:10,21:00,9h 20m,1 stop,"₹22,760",05 May
16,IndiGo,GOI,GOI → DEL → AUH,19:15,23:406 May,29h 55m,1 stop,"₹23,233",05 May
17,IndiGo,GOI,GOI → HYD → SHJ,15:15,21:55,8h 10m,1 stop,"₹23,495",05 May
18,SpiceJet,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹23,634",05 May
19,SpiceJet,GOI,GOI → DEL → DXB,18:10,10:106 May,17h 30m,1 stop,"₹24,355",05 May
20,IndiGo,GOI,GOI → LKO → DXB,18:30,04:156 May,11h 15m,1 stop,"₹24,755",05 May
21,SpiceJet,GOI,GOI → DEL → DXB,23:00,18:256 May,20h 55m,1 stop,"₹26,351",05 May
22,Air India,GOI,GOI → BOM → MAA → DXB,06:50,21:30,16h 10m,2 stops,"₹28,436",05 May
23,Air India,GOI,GOI → BOM → DEL → DXB,06:50,19:00,13h 40m,2 stops,"₹29,486",05 May
24,IndiGo,GOI,GOI → AMD → DXB,20:15,03:256 May,8h 40m,1 stop,"₹30,110",05 May
25,Air India,GOI,GOI → DXB,20:00,22:00,3h 30m,non-stop,"₹31,407",05 May
26,Multiple carrier,GOI,GOI → DEL → AUH → XNB,21:55,10:206 May,13h 55m,2 stops,"₹37,107",05 May
27,Air India,GOI,GOI → BOM → DXB,15:15,21:55,8h 10m,1 stop,"₹37,886",05 May
28,Air India,GOI,GOI → DEL → BOM → DXB,14:15,02:406 May,13h 55m,2 stops,"₹38,201",05 May
29,Multiple carrier,GOI,GOI → BOM → DXB,13:20,21:00,9h 10m,1 stop,"₹40,983",05 May
30,Hahn Air,GOI,GOI → BOM → DXB,17:35,00:406 May,8h 35m,1 stop,"₹42,373",05 May
31,Hahn Air,GOI,GOI → DEL → DXB,23:00,10:106 May,12h 40m,1 stop,"₹45,670",05 May
32,Hahn Air,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹46,447",05 May
33,Multiple carrier,BLR,BLR → CMB → DOH → SHJ,21:10,16:356 May,20h 55m,2 stops,"₹51,950",05 May
34,Air India,GOI,GOI → DEL → DXB,14:15,22:45,10h 0m,1 stop,"₹53,058",05 May
35,Multiple carrier,GOI,GOI → BOM → DXB,13:20,00:056 May,12h 15m,1 stop,"₹59,069",05 May
36,Hahn Air,GOI,GOI → BOM → DEL → DXB,03:45,18:25,16h 10m,2 stops,"₹60,212",05 May
37,Multiple carrier,BLR,BLR → CMB → DOH → SHJ,21:10,16:356 May,20h 55m,2 stops,"₹61,841",05 May
38,Qatar Airways,GOI,GOI → DOH → SHJ,03:40,09:50,7h 40m,1 stop,"₹62,891",05 May
39,Hahn Air,GOI,GOI → DEL → BOM → DXB,15:05,00:406 May,11h 5m,2 stops,"₹63,425",05 May
40,Multiple carrier,GOI,GOI → BOM → AUH → XNB,13:20,02:156 May,14h 25m,2 stops,"₹66,019",05 May
41,Multiple carrier,GOI,GOI → HYD → DXB,21:05,12:106 May,16h 35m,1 stop,"₹73,217",05 May
42,Qatar Airways,GOI,GOI → DOH → DXB,03:40,21:30,19h 20m,1 stop,"₹73,687",05 May
43,Multiple carrier,BLR,BLR → CMB → DOH → SHJ,21:10,16:356 May,20h 55m,2 stops,"₹80,142",05 May
44,Multiple carrier,GOI,GOI → BOM → DXB,17:35,00:056 May,8h 0m,1 stop,"₹83,477",05 May
45,Multiple carrier,GOI,GOI → BOM → DXB,13:20,06:006 May,18h 10m,1 stop,"₹83,477",05 May
46,Multiple carrier,GOI,GOI → DEL → DXB,21:55,06:206 May,9h 55m,1 stop,"₹85,550",05 May
47,Multiple carrier,GOI,GOI → DEL → DXB,18:10,06:206 May,13h 40m,1 stop,"₹85,550",05 May
48,Multiple carrier,BLR,BLR → CMB → DOH → SHJ,21:10,09:506 May,14h 10m,2 stops,"₹85,770",05 May
49,Multiple carrier,GOI,GOI → DEL → BAH → DXB,21:55,12:056 May,15h 40m,2 stops,"₹86,789",05 May
50,Qatar Airways,GOI,GOI → DOH → DXB,03:40,20:55,18h 45m,1 stop,"₹86,986",05 May
51,Multiple carrier,GOI,GOI → HYD → DXB,21:05,06:406 May,11h 5m,1 stop,"₹88,123",05 May
52,Multiple carrier,GOI,GOI → BLR → DXB,22:50,06:506 May,9h 30m,1 stop,"₹90,842",05 May
53,Qatar Airways,BLR,BLR → DOH → SHJ,03:55,09:50,7h 25m,1 stop,"₹91,997",05 May
54,Multiple carrier,GOI,GOI → DEL → AUH → XNB,14:25,03:256 May,14h 30m,2 stops,"₹1,14,545",05 May
55,Multiple carrier,GOI,GOI → DOH → MCT → DXB,03:40,15:40,13h 30m,2 stops,"₹1,18,756",05 May
56,Multiple carrier,GOI,GOI → BLR → AUH → XNB,14:40,02:156 May,13h 5m,2 stops,"₹1,40,972",05 May
57,Multiple carrier,GOI,GOI → DEL → AUH → XNB,14:25,02:156 May,13h 20m,2 stops,"₹1,96,517",05 May
58,Multiple carrier,GOI,GOI → LHR → DXB,06:25,00:206 May,19h 25m,1 stop,"₹3,46,311",05 May

In [133]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('7 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df17=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [134]:
df17['Date Of Journey'] = '06 May'
df17

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,GOI,GOI → BOM → AUH,06:45,23:25,18h 10m,1 stop,"₹18,455",06 May
1,GO FIRST,GOI,GOI → BOM → AUH,06:40,22:10,17h 0m,1 stop,"₹18,955",06 May
2,IndiGo,GOI,GOI → BLR → DXB,02:25,10:50,9h 55m,1 stop,"₹20,240",06 May
3,GO FIRST,GOI,GOI → BOM → AUH,13:15,22:10,10h 25m,1 stop,"₹20,531",06 May
4,IndiGo,GOI,GOI → BOM → AUH,16:30,23:25,8h 25m,1 stop,"₹20,555",06 May
5,IndiGo,GOI,GOI → HYD → SHJ,15:15,21:55,8h 10m,1 stop,"₹20,713",06 May
6,IndiGo,GOI,GOI → BOM → DXB,06:45,16:55,11h 40m,1 stop,"₹20,765",06 May
7,IndiGo,GOI,GOI → BOM → AUH,18:40,23:25,6h 15m,1 stop,"₹21,185",06 May
8,IndiGo,GOI,GOI → BOM → DXB,00:10,10:25,11h 45m,1 stop,"₹21,500",06 May
9,IndiGo,GOI,GOI → BOM → AUH,13:10,23:25,11h 45m,1 stop,"₹21,710",06 May
10,SpiceJet,GOI,GOI → BOM → DXB,13:30,00:407 May,12h 40m,1 stop,"₹21,952",06 May
11,IndiGo,GOI,GOI → ATQ → SHJ,23:05,14:457 May,17h 10m,1 stop,"₹22,550",06 May
12,IndiGo,GOI,GOI → HYD → DXB,02:05,09:10,8h 35m,1 stop,"₹22,708",06 May
13,IndiGo,GOI,GOI → HYD → SHJ,14:30,21:55,8h 55m,1 stop,"₹23,075",06 May
14,IndiGo,GOI,GOI → DEL → AUH,15:25,23:40,9h 45m,1 stop,"₹23,233",06 May
15,IndiGo,GOI,GOI → BOM → DXB,13:10,21:00,9h 20m,1 stop,"₹24,020",06 May
16,IndiGo,GOI,GOI → BOM → DXB,18:40,04:007 May,10h 50m,1 stop,"₹24,230",06 May
17,SpiceJet,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹25,314",06 May
18,IndiGo,GOI,GOI → HYD → DXB,22:00,09:107 May,12h 40m,1 stop,"₹26,278",06 May
19,IndiGo,GOI,GOI → LKO → DXB,18:30,04:157 May,11h 15m,1 stop,"₹26,435",06 May
20,IndiGo,GOI,GOI → AMD → DXB,20:15,03:257 May,8h 40m,1 stop,"₹27,433",06 May
21,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹28,149",06 May
22,Air India,GOI,GOI → BOM → MAA → DXB,06:50,21:30,16h 10m,2 stops,"₹28,436",06 May
23,SpiceJet,GOI,GOI → DEL → DXB,18:10,10:107 May,17h 30m,1 stop,"₹28,765",06 May
24,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹29,079",06 May
25,Air India,GOI,GOI → BOM → DEL → DXB,06:50,19:00,13h 40m,2 stops,"₹29,486",06 May
26,SpiceJet,GOI,GOI → DEL → DXB,23:00,18:257 May,20h 55m,1 stop,"₹31,601",06 May
27,Air India,GOI,GOI → BOM → DXB,15:15,21:55,8h 10m,1 stop,"₹37,886",06 May
28,Air India,GOI,GOI → DEL → BOM → DXB,14:15,02:407 May,13h 55m,2 stops,"₹38,201",06 May
29,Multiple carrier,GOI,GOI → BOM → AUH,13:20,22:25,10h 35m,1 stop,"₹40,730",06 May
30,Multiple carrier,GOI,GOI → BOM → DXB,13:20,21:00,9h 10m,1 stop,"₹46,664",06 May
31,Hahn Air,GOI,GOI → BOM → DXB,13:30,00:407 May,12h 40m,1 stop,"₹47,098",06 May
32,Hahn Air,GOI,GOI → BOM → DXB,17:35,00:407 May,8h 35m,1 stop,"₹47,518",06 May
33,Hahn Air,GOI,GOI → AMD → DXB,07:50,23:10,16h 50m,1 stop,"₹48,127",06 May
34,Hahn Air,GOI,GOI → DEL → DXB,23:00,10:107 May,12h 40m,1 stop,"₹50,080",06 May
35,Air India,GOI,GOI → DEL → DXB,14:15,22:45,10h 0m,1 stop,"₹53,058",06 May
36,Qatar Airways,GOI,GOI → DOH → SHJ,03:40,16:35,14h 25m,1 stop,"₹57,599",06 May
37,Qatar Airways,GOI,GOI → DOH → DXB,03:40,21:30,19h 20m,1 stop,"₹57,874",06 May
38,Hahn Air,GOI,GOI → BOM → DEL → DXB,03:45,18:25,16h 10m,2 stops,"₹60,212",06 May
39,Qatar Airways,GOI,GOI → DOH → SHJ,03:40,09:50,7h 40m,1 stop,"₹64,519",06 May
40,Air India,GOI,GOI → DEL → DXB,14:15,13:457 May,25h 0m,1 stop,"₹65,658",06 May
41,Multiple carrier,GOI,GOI → HYD → DXB,08:05,00:107 May,17h 35m,1 stop,"₹65,830",06 May
42,Hahn Air,GOI,GOI → DEL → BOM → DXB,15:05,00:407 May,11h 5m,2 stops,"₹68,150",06 May
43,Qatar Airways,GOI,GOI → DOH → DXB,03:40,20:55,18h 45m,1 stop,"₹75,394",06 May
44,Multiple carrier,GOI,GOI → BOM → DXB,13:30,21:00,9h 0m,1 stop,"₹84,632",06 May
45,Multiple carrier,GOI,GOI → BOM → DXB → ZVJ,13:20,05:157 May,17h 25m,2 stops,"₹84,632",06 May
46,Multiple carrier,GOI,GOI → DEL → DXB,15:05,23:55,10h 20m,1 stop,"₹86,705",06 May
47,Multiple carrier,GOI,GOI → DEL → DXB,14:25,23:55,11h 0m,1 stop,"₹86,705",06 May
48,Multiple carrier,GOI,GOI → DEL → BAH → DXB,14:25,04:157 May,15h 20m,2 stops,"₹87,220",06 May
49,Multiple carrier,GOI,GOI → HYD → DXB,21:05,12:107 May,16h 35m,1 stop,"₹89,278",06 May
50,Multiple carrier,GOI,GOI → BLR → AUH,14:40,07:057 May,17h 55m,1 stop,"₹1,40,036",06 May
51,Multiple carrier,GOI,GOI → DEL → AUH,14:25,23:20,10h 25m,1 stop,"₹1,66,730",06 May
52,Multiple carrier,GOI,GOI → HYD → DXB,21:05,06:407 May,11h 5m,1 stop,"₹1,77,203",06 May
53,Multiple carrier,GOI,GOI → DEL → DXB,21:55,06:207 May,9h 55m,1 stop,"₹1,80,423",06 May
54,Multiple carrier,GOI,GOI → BLR → DXB,22:50,12:457 May,15h 25m,1 stop,"₹1,80,658",06 May
55,Multiple carrier,GOI,GOI → DEL → DXB,18:10,06:207 May,13h 40m,1 stop,"₹1,81,750",06 May
56,Multiple carrier,GOI,GOI → DEL → DOH → SHJ,21:55,16:357 May,20h 10m,2 stops,"₹2,11,387",06 May
57,Multiple carrier,GOI,GOI → LHR → AUH,04:35,00:357 May,21h 30m,1 stop,"₹3,31,244",06 May
58,Multiple carrier,GOI,GOI → LHR → DXB,04:35,23:05,20h 0m,1 stop,"₹3,57,217",06 May

In [135]:
Flight2=pd.concat([df11,df12,df13,df14,df15,df16,df17])
Flight2['Destination'] = 'DXB'
Flight2

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey,Destination
0,Oman Av (SAOG),GOI,GOI → MCT → DXB,21:00,09:501 May,14h 20m,1 stop,"₹11,632",30 Apr,DXB
1,Air India,BLR,BLR → GOI → DXB,17:00,22:00,6h 30m,1 stop,"₹13,210",30 Apr,DXB
2,SriLankan Airlines,BLR,BLR → CMB → DXB,03:30,21:40,19h 40m,1 stop,"₹13,420",30 Apr,DXB
3,Air India,GOI,GOI → DXB,20:00,22:00,3h 30m,non-stop,"₹13,557",30 Apr,DXB
4,Air Arabia,GOI,GOI → SHJ,04:45,06:30,3h 15m,non-stop,"₹13,803",30 Apr,DXB
...,...,...,...,...,...,...,...,...,...,...
54,Multiple carrier,GOI,GOI → BLR → DXB,22:50,12:457 May,15h 25m,1 stop,"₹1,80,658",06 May,DXB
55,Multiple carrier,GOI,GOI → DEL → DXB,18:10,06:207 May,13h 40m,1 stop,"₹1,81,750",06 May,DXB
56,Multiple carrier,GOI,GOI → DEL → DOH → SHJ,21:55,16:357 May,20h 10m,2 stops,"₹2,11,387",06 May,DXB
57,Multiple carrier,GOI,GOI → LHR → AUH,04:35,00:357 May,21h 30m,1 stop,"₹3,31,244",06 May,DXB
58,Multiple carrier,GOI,GOI → LHR → DXB,04:35,23:05,20h 0m,1 stop,"₹3,57,217",06 May,DXB

In [85]:
# Mumbai-Singapore Flight Details

In [90]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('1 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df18=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [91]:
df18['Date Of Journey'] = '30 Apr'
df18

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,BOM → CMB → SIN,03:10,18:55,13h 15m,1 stop,"₹16,285",30 Apr
1,IndiGo,BOM,BOM → CCU → SIN,17:35,04:301 May,8h 25m,1 stop,"₹17,722",30 Apr
2,IndiGo,BOM,BOM → CCU → SIN,12:55,04:301 May,13h 5m,1 stop,"₹18,772",30 Apr
3,IndiGo,BOM,BOM → BLR → SIN,14:40,03:201 May,10h 10m,1 stop,"₹22,447",30 Apr
4,IndiGo,BOM,BOM → BLR → SIN,11:45,03:201 May,13h 5m,1 stop,"₹24,022",30 Apr
5,Thai Airways,BOM,BOM → BKK → SIN,23:35,11:151 May,9h 10m,1 stop,"₹24,627",30 Apr
6,SriLankan Airlines,BOM,BOM → CMB → SIN,20:40,18:551 May,19h 45m,1 stop,"₹27,058",30 Apr
7,IndiGo,BOM,BOM → MAA → SIN,16:45,05:101 May,9h 55m,1 stop,"₹27,062",30 Apr
8,Air India,BOM,BOM → GOI → DEL → SIN,05:05,07:252 May,47h 50m,2 stops,"₹27,406",30 Apr
9,Air India,BOM,BOM → GOI → DEL → SIN,21:00,07:252 May,31h 55m,2 stops,"₹27,616",30 Apr
10,Air India,BOM,BOM → DEL → SIN,19:00,07:251 May,9h 55m,1 stop,"₹29,926",30 Apr
11,Multiple carrier,BOM,BOM → MAA → CMB → SIN,09:45,18:551 May,30h 40m,2 stops,"₹31,606",30 Apr
12,Singapore Air,BOM,BOM → SIN,11:45,19:50,5h 35m,non-stop,"₹35,377",30 Apr
13,Air India,BOM,BOM → MAA → SIN,05:25,18:10,10h 15m,1 stop,"₹35,491",30 Apr
14,Air India,BOM,BOM → DEL → MAA → SIN,19:00,18:101 May,20h 40m,2 stops,"₹36,016",30 Apr
15,Vistara,BOM,BOM → DEL → SIN,18:30,08:151 May,11h 15m,1 stop,"₹36,167",30 Apr
16,Vistara,BOM,BOM → DEL → SIN,15:45,08:151 May,14h 0m,1 stop,"₹36,409",30 Apr
17,Air India,BOM,BOM → SIN,23:50,07:501 May,5h 30m,non-stop,"₹36,545",30 Apr
18,Vistara,BOM,BOM → DEL → SIN,19:45,08:151 May,10h 0m,1 stop,"₹36,571",30 Apr
19,Air India,BOM,BOM → DEL → MAA → SIN,10:00,18:101 May,29h 40m,2 stops,"₹37,591",30 Apr
20,Gulf Air,BOM,BOM → BAH → SIN,21:45,12:401 May,12h 25m,1 stop,"₹38,040",30 Apr
21,Air India,BOM,BOM → GOI → DEL → SIN,05:05,07:251 May,23h 50m,2 stops,"₹43,051",30 Apr
22,Vistara,BOM,BOM → DEL → SIN,10:25,08:151 May,19h 20m,1 stop,"₹45,087",30 Apr
23,Malaysia Airlines,BOM,BOM → KUL → SIN,23:35,13:301 May,11h 25m,1 stop,"₹51,602",30 Apr
24,Air India,BOM,BOM → DEL → SIN,10:00,07:251 May,18h 55m,1 stop,"₹59,378",30 Apr
25,Singapore Air,BOM,BOM → SIN,23:40,07:401 May,5h 30m,non-stop,"₹63,517",30 Apr
26,Multiple carrier,BOM,BOM → KUL → SIN,23:35,11:351 May,9h 30m,1 stop,"₹68,239",30 Apr
27,Multiple carrier,BOM,BOM → HYD → SIN,19:20,06:101 May,8h 20m,1 stop,"₹88,799",30 Apr
28,Multiple carrier,BOM,BOM → CCU → SIN,14:05,06:401 May,14h 5m,1 stop,"₹89,744",30 Apr
29,Multiple carrier,BOM,BOM → MAA → SIN,17:50,06:101 May,9h 50m,1 stop,"₹94,889",30 Apr
30,Multiple carrier,BOM,BOM → BLR → SIN,19:10,06:101 May,8h 30m,1 stop,"₹96,440",30 Apr
31,Multiple carrier,BOM,BOM → CMB → SIN,20:40,07:201 May,8h 10m,1 stop,"₹1,02,341",30 Apr
32,Multiple carrier,BOM,BOM → DEL → SIN,10:25,06:101 May,17h 15m,1 stop,"₹1,06,229",30 Apr
33,Multiple carrier,BOM,BOM → DEL → SIN,14:40,06:101 May,13h 0m,1 stop,"₹1,10,278",30 Apr
34,Multiple carrier,BOM,BOM → DEL → SIN,15:45,06:101 May,11h 55m,1 stop,"₹1,20,159",30 Apr
35,Malaysia Airlines,BOM,BOM → KUL → SIN,23:35,09:551 May,7h 50m,1 stop,"₹1,32,593",30 Apr
36,Malaysia Airlines,BOM,BOM → KUL → SIN,23:35,21:501 May,19h 45m,1 stop,"₹1,34,104",30 Apr
37,Qatar Airways,BOM,BOM → DOH → SIN,18:35,15:451 May,18h 40m,1 stop,"₹1,59,794",30 Apr
38,Multiple carrier,BOM,BOM → DEL → SIN,19:45,17:251 May,19h 10m,1 stop,"₹1,98,447",30 Apr
39,British Airways,BOM,BOM → LHR → SIN,13:10,17:451 May,26h 5m,1 stop,"₹2,55,606",30 Apr
40,All Nippon,BOM,BOM → NRT → SIN,19:40,17:201 May,19h 10m,1 stop,"₹3,14,698",30 Apr
41,Emirates,BOM,BOM → DXB → SIN,19:20,20:551 May,23h 5m,1 stop,"₹3,43,159",30 Apr
42,Lufthansa,BOM,BOM → MUC → SIN,00:50,07:001 May,27h 40m,1 stop,"₹3,68,450",30 Apr

In [92]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('2 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df19=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [93]:
df19['Date Of Journey'] = '01 May'
df19

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → BLR → SIN,14:40,03:202 May,10h 10m,1 stop,"₹13,312",01 May
1,Air India,BOM,BOM → DEL → SIN,19:00,07:252 May,9h 55m,1 stop,"₹14,281",01 May
2,IndiGo,BOM,BOM → MAA → SIN,22:15,11:202 May,10h 35m,1 stop,"₹15,832",01 May
3,IndiGo,BOM,BOM → CCU → SIN,17:35,04:302 May,8h 25m,1 stop,"₹16,777",01 May
4,IndiGo,BOM,BOM → MAA → SIN,00:20,11:20,8h 30m,1 stop,"₹17,722",01 May
5,Air India,BOM,BOM → SIN,23:50,07:502 May,5h 30m,non-stop,"₹20,480",01 May
6,IndiGo,BOM,BOM → MAA → SIN,16:45,05:102 May,9h 55m,1 stop,"₹21,082",01 May
7,Air India,BOM,BOM → MAA → SIN,05:25,18:10,10h 15m,1 stop,"₹23,626",01 May
8,Vistara,BOM,BOM → SIN,02:30,10:45,5h 45m,non-stop,"₹24,386",01 May
9,Air India,BOM,BOM → BLR → DEL → SIN,06:50,07:252 May,22h 5m,2 stops,"₹24,991",01 May
10,Air India,BOM,BOM → BLR → DEL → SIN,09:30,07:252 May,19h 25m,2 stops,"₹25,201",01 May
11,Air India,BOM,BOM → GOI → DEL → SIN,05:05,07:252 May,23h 50m,2 stops,"₹27,406",01 May
12,Air India,BOM,BOM → BLR → DEL → SIN,06:50,07:253 May,46h 5m,2 stops,"₹35,911",01 May
13,Air India,BOM,BOM → BLR → DEL → SIN,09:30,07:253 May,43h 25m,2 stops,"₹36,121",01 May
14,Air India,BOM,BOM → GOI → DEL → SIN,05:05,07:253 May,47h 50m,2 stops,"₹38,326",01 May
15,Air India,BOM,BOM → GOI → DEL → SIN,21:00,07:253 May,31h 55m,2 stops,"₹38,536",01 May
16,Vistara,BOM,BOM → DEL → SIN,19:45,08:152 May,10h 0m,1 stop,"₹41,417",01 May
17,Vistara,BOM,BOM → DEL → SIN,18:30,08:152 May,11h 15m,1 stop,"₹41,659",01 May
18,Vistara,BOM,BOM → DEL → SIN,11:55,08:152 May,17h 50m,1 stop,"₹41,821",01 May
19,Vistara,BOM,BOM → DEL → SIN,14:40,08:152 May,15h 5m,1 stop,"₹42,383",01 May
20,Air India,BOM,BOM → DEL → MAA → SIN,19:00,18:102 May,20h 40m,2 stops,"₹43,681",01 May
21,Air India,BOM,BOM → IXU → DEL → SIN,15:25,07:252 May,13h 30m,2 stops,"₹43,733",01 May
22,Thai Airways,BOM,BOM → BKK → SIN,23:35,11:152 May,9h 10m,1 stop,"₹47,097",01 May
23,Air India,BOM,BOM → DEL → MAA → SIN,18:00,18:102 May,21h 40m,2 stops,"₹47,881",01 May
24,Singapore Air,BOM,BOM → SIN,23:40,07:402 May,5h 30m,non-stop,"₹51,862",01 May
25,Malaysia Airlines,BOM,BOM → KUL → SIN,23:35,13:502 May,11h 45m,1 stop,"₹58,359",01 May
26,Malaysia Airlines,BOM,BOM → KUL → SIN,23:35,13:302 May,11h 25m,1 stop,"₹65,866",01 May
27,Multiple carrier,BOM,BOM → CCU → SIN,14:05,06:402 May,14h 5m,1 stop,"₹86,279",01 May
28,Multiple carrier,BOM,BOM → CCU → SIN,17:20,06:402 May,10h 50m,1 stop,"₹87,854",01 May
29,Multiple carrier,BOM,BOM → HYD → SIN,19:20,06:102 May,8h 20m,1 stop,"₹88,799",01 May
30,Multiple carrier,BOM,BOM → KUL → SIN,23:35,09:552 May,7h 50m,1 stop,"₹94,143",01 May
31,Multiple carrier,BOM,BOM → MAA → SIN,17:50,06:102 May,9h 50m,1 stop,"₹94,889",01 May
32,Multiple carrier,BOM,BOM → KUL → SIN,23:35,21:502 May,19h 45m,1 stop,"₹94,917",01 May
33,Multiple carrier,BOM,BOM → BLR → SIN,19:10,06:102 May,8h 30m,1 stop,"₹96,440",01 May
34,Multiple carrier,BOM,BOM → BLR → SIN,17:30,06:102 May,10h 10m,1 stop,"₹97,724",01 May
35,Multiple carrier,BOM,BOM → DEL → SIN,14:40,06:102 May,13h 0m,1 stop,"₹1,01,504",01 May
36,Multiple carrier,BOM,BOM → BKK → SIN,12:45,11:152 May,20h 0m,1 stop,"₹1,04,177",01 May
37,Multiple carrier,BOM,BOM → CMB → SIN,20:40,07:202 May,8h 10m,1 stop,"₹1,06,494",01 May
38,Qatar Airways,BOM,BOM → DOH → SIN,18:35,15:452 May,18h 40m,1 stop,"₹1,06,947",01 May
39,Emirates,BOM,BOM → DXB → SIN,22:20,15:002 May,14h 10m,1 stop,"₹1,17,061",01 May
40,Multiple carrier,BOM,BOM → BKK → SIN,12:45,23:30,8h 15m,1 stop,"₹1,47,112",01 May
41,Multiple carrier,BOM,BOM → BKK → SIN,12:45,11:152 May,20h 0m,1 stop,"₹1,49,512",01 May
42,Emirates,BOM,BOM → DXB → SIN,05:10,20:55,13h 15m,1 stop,"₹2,06,615",01 May
43,British Airways,BOM,BOM → LHR → SIN,13:10,17:452 May,26h 5m,1 stop,"₹2,13,733",01 May
44,Lufthansa,BOM,BOM → FRA → SIN,02:50,16:452 May,35h 25m,1 stop,"₹3,26,105",01 May
45,Multiple carrier,BOM,BOM → LHR → SIN,13:10,16:552 May,25h 15m,1 stop,"₹3,36,755",01 May
46,Emirates,BOM,BOM → DXB → SIN,04:30,20:55,13h 55m,1 stop,"₹3,43,159",01 May
47,Lufthansa,BOM,BOM → FRA → SIN,02:50,06:502 May,25h 30m,1 stop,"₹3,83,932",01 May
48,Multiple carrier,BOM,BOM → LHR → SIN,06:30,16:552 May,31h 55m,1 stop,"₹4,17,708",01 May
49,Multiple carrier,BOM,BOM → LHR → SIN,06:30,17:452 May,32h 45m,1 stop,"₹4,37,716",01 May

In [94]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('3 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df20=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [95]:
df20['Date Of Journey'] = '02 May'
df20

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → MAA → SIN,00:20,11:20,8h 30m,1 stop,"₹15,832",02 May
1,IndiGo,BOM,BOM → BLR → SIN,14:40,03:203 May,10h 10m,1 stop,"₹16,777",02 May
2,IndiGo,BOM,BOM → BLR → SIN,11:45,03:203 May,13h 5m,1 stop,"₹17,722",02 May
3,IndiGo,BOM,BOM → MAA → SIN,22:15,11:203 May,10h 35m,1 stop,"₹18,772",02 May
4,IndiGo,BOM,BOM → MAA → SIN,19:40,11:203 May,13h 10m,1 stop,"₹19,822",02 May
5,Vistara,BOM,BOM → SIN,02:30,10:45,5h 45m,non-stop,"₹20,711",02 May
6,IndiGo,BOM,BOM → BLR → SIN,09:55,03:203 May,14h 55m,1 stop,"₹21,082",02 May
7,Air India,BOM,BOM → SIN,23:50,07:503 May,5h 30m,non-stop,"₹23,420",02 May
8,IndiGo,BOM,BOM → MAA → SIN,16:45,05:103 May,9h 55m,1 stop,"₹24,022",02 May
9,Air India,BOM,BOM → DEL → SIN,19:00,07:253 May,9h 55m,1 stop,"₹25,201",02 May
10,Singapore Air,BOM,BOM → SIN,23:40,07:403 May,5h 30m,non-stop,"₹35,377",02 May
11,Thai Airways,BOM,BOM → BKK → SIN,23:35,11:153 May,9h 10m,1 stop,"₹35,458",02 May
12,Air India,BOM,BOM → MAA → SIN,05:25,18:10,10h 15m,1 stop,"₹35,491",02 May
13,Air India,BOM,BOM → BLR → DEL → SIN,09:30,07:253 May,19h 25m,2 stops,"₹35,911",02 May
14,Vistara,BOM,BOM → DEL → SIN,19:45,08:153 May,10h 0m,1 stop,"₹36,167",02 May
15,Vistara,BOM,BOM → DEL → SIN,08:45,08:153 May,21h 0m,1 stop,"₹36,409",02 May
16,Air India,BOM,BOM → GOI → DEL → SIN,05:05,07:253 May,23h 50m,2 stops,"₹38,326",02 May
17,Air India,BOM,BOM → DEL → MAA → SIN,19:00,18:103 May,20h 40m,2 stops,"₹39,586",02 May
18,Air India,BOM,BOM → DEL → MAA → SIN,08:00,18:103 May,31h 40m,2 stops,"₹39,796",02 May
19,SriLankan Airlines,BOM,BOM → CMB → SIN,20:40,18:553 May,19h 45m,1 stop,"₹46,430",02 May
20,Singapore Air,BOM,BOM → SIN,11:45,19:50,5h 35m,non-stop,"₹51,862",02 May
21,Multiple carrier,BOM,BOM → MAA → CMB → SIN,21:00,18:553 May,19h 25m,2 stops,"₹54,470",02 May
22,Multiple carrier,BOM,BOM → CCU → SIN,14:05,06:403 May,14h 5m,1 stop,"₹86,279",02 May
23,Multiple carrier,BOM,BOM → MAA → SIN,09:45,06:103 May,17h 55m,1 stop,"₹94,889",02 May
24,Multiple carrier,BOM,BOM → DEL → SIN,17:35,06:103 May,10h 5m,1 stop,"₹96,440",02 May
25,Multiple carrier,BOM,BOM → BLR → SIN,19:10,06:103 May,8h 30m,1 stop,"₹98,669",02 May
26,Multiple carrier,BOM,BOM → CMB → SIN,20:40,07:203 May,8h 10m,1 stop,"₹1,02,341",02 May
27,Multiple carrier,BOM,BOM → MAA → SIN,17:50,06:103 May,9h 50m,1 stop,"₹1,58,127",02 May
28,Qatar Airways,BOM,BOM → DOH → SIN,18:35,15:453 May,18h 40m,1 stop,"₹1,69,617",02 May
29,Multiple carrier,BOM,BOM → MLE → SIN,13:30,07:053 May,15h 5m,1 stop,"₹1,89,689",02 May
30,British Airways,BOM,BOM → LHR → SIN,13:10,17:453 May,26h 5m,1 stop,"₹2,89,470",02 May
31,Multiple carrier,BOM,BOM → LHR → SIN,13:10,16:553 May,25h 15m,1 stop,"₹3,82,201",02 May
32,Multiple carrier,BOM,BOM → LHR → SIN,10:15,16:553 May,28h 10m,1 stop,"₹4,17,708",02 May
33,Multiple carrier,BOM,BOM → LHR → SIN,10:15,17:453 May,29h 0m,1 stop,"₹4,37,716",02 May
34,Multiple carrier,BOM,BOM → ZRH → SIN,05:15,05:553 May,22h 10m,1 stop,"₹4,55,692",02 May
35,Lufthansa,BOM,BOM → MUC → SIN,00:50,07:003 May,27h 40m,1 stop,"₹4,95,186",02 May
36,Multiple carrier,BOM,BOM → MUC → SIN,00:50,07:003 May,27h 40m,1 stop,"₹6,01,907",02 May

In [96]:
Flight3=pd.concat([df18,df19,df20])
Flight3['Destination'] = 'SIN'
Flight3

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey,Destination
0,SriLankan Airlines,BOM,BOM → CMB → SIN,03:10,18:55,13h 15m,1 stop,"₹16,285",30 Apr,SIN
1,IndiGo,BOM,BOM → CCU → SIN,17:35,04:301 May,8h 25m,1 stop,"₹17,722",30 Apr,SIN
2,IndiGo,BOM,BOM → CCU → SIN,12:55,04:301 May,13h 5m,1 stop,"₹18,772",30 Apr,SIN
3,IndiGo,BOM,BOM → BLR → SIN,14:40,03:201 May,10h 10m,1 stop,"₹22,447",30 Apr,SIN
4,IndiGo,BOM,BOM → BLR → SIN,11:45,03:201 May,13h 5m,1 stop,"₹24,022",30 Apr,SIN
...,...,...,...,...,...,...,...,...,...,...
32,Multiple carrier,BOM,BOM → LHR → SIN,10:15,16:553 May,28h 10m,1 stop,"₹4,17,708",02 May,SIN
33,Multiple carrier,BOM,BOM → LHR → SIN,10:15,17:453 May,29h 0m,1 stop,"₹4,37,716",02 May,SIN
34,Multiple carrier,BOM,BOM → ZRH → SIN,05:15,05:553 May,22h 10m,1 stop,"₹4,55,692",02 May,SIN
35,Lufthansa,BOM,BOM → MUC → SIN,00:50,07:003 May,27h 40m,1 stop,"₹4,95,186",02 May,SIN
36,Multiple carrier,BOM,BOM → MUC → SIN,00:50,07:003 May,27h 40m,1 stop,"₹6,01,907",02 May,SIN

In [19]:
# Mumbai-Dubai Flight Details

In [97]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('2 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df21=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [98]:
df21['Date Of Journey'] = '01 May'
df21

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹9,595",01 May
1,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹9,806",01 May
2,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹9,989",01 May
3,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹10,232",01 May
4,SpiceJet,BOM,BOM → DXB,23:05,00:402 May,3h 5m,non-stop,"₹10,529",01 May
...,...,...,...,...,...,...,...,...,...
88,British Airways,BOM,BOM → LHR → DXB,13:10,07:302 May,19h 50m,1 stop,"₹2,21,674",01 May
89,Multiple carrier,BOM,BOM → LHR → AUH,12:15,06:152 May,19h 30m,1 stop,"₹2,91,419",01 May
90,Multiple carrier,BOM,BOM → LHR → AUH,13:10,06:152 May,18h 35m,1 stop,"₹2,94,632",01 May
91,Multiple carrier,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹3,83,995",01 May
92,Lufthansa,BOM,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹4,12,435",01 May

In [99]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)  
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('3 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df22=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [100]:
df22['Date Of Journey'] = '02 May'
df22

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹9,595",02 May
1,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹9,806",02 May
2,Air India Express,BOM,BOM → SHJ,06:20,08:00,3h 10m,non-stop,"₹9,989",02 May
3,SpiceJet,BOM,BOM → DXB,23:05,00:403 May,3h 5m,non-stop,"₹10,532",02 May
4,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹10,581",02 May
...,...,...,...,...,...,...,...,...,...
83,British Airways,BOM,BOM → LHR → DXB,13:10,07:303 May,19h 50m,1 stop,"₹2,53,270",02 May
84,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹2,57,041",02 May
85,Multiple carrier,BOM,BOM → LHR → AUH,12:15,06:153 May,19h 30m,1 stop,"₹2,91,419",02 May
86,Multiple carrier,BOM,BOM → LHR → AUH,13:10,06:153 May,18h 35m,1 stop,"₹3,25,127",02 May
87,Swiss Intl Air,BOM,BOM → ZRH → DXB,05:15,21:30,17h 45m,1 stop,"₹4,31,459",02 May

In [101]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('4 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df23=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [102]:
df23['Date Of Journey'] = '03 May'
df23

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹9,595",03 May
1,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹9,806",03 May
2,IndiGo,BOM,BOM → DXB,02:25,04:00,3h 5m,non-stop,"₹9,910",03 May
3,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹9,989",03 May
4,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹10,232",03 May
...,...,...,...,...,...,...,...,...,...
97,British Airways,BOM,BOM → LHR → DXB,13:10,07:304 May,19h 50m,1 stop,"₹2,53,270",03 May
98,Multiple carrier,BOM,BOM → LHR → AUH,12:15,06:154 May,19h 30m,1 stop,"₹2,91,419",03 May
99,Multiple carrier,BOM,BOM → LHR → AUH,13:10,06:154 May,18h 35m,1 stop,"₹3,25,127",03 May
100,Lufthansa,BOM,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹4,12,435",03 May
101,Lufthansa,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,53,482",03 May

In [103]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)   
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('5 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df24=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [104]:
df24['Date Of Journey'] = '04 May'
df24

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹11,632",04 May
1,IndiGo,BOM,BOM → DXB,02:25,04:00,3h 5m,non-stop,"₹12,115",04 May
2,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹12,194",04 May
3,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹13,212",04 May
4,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹14,053",04 May
...,...,...,...,...,...,...,...,...,...
97,Multiple carrier,BOM,BOM → LHR → AUH,12:15,06:155 May,19h 30m,1 stop,"₹3,21,700",04 May
98,Multiple carrier,BOM,BOM → LHR → AUH,13:10,06:155 May,18h 35m,1 stop,"₹3,25,127",04 May
99,Lufthansa,BOM,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹3,97,275",04 May
100,Swiss Intl Air,BOM,BOM → ZRH → DXB,05:15,21:30,17h 45m,1 stop,"₹4,31,459",04 May
101,Lufthansa,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,35,784",04 May

In [107]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('6 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df25=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [108]:
df25['Date Of Journey'] = '05 May'
df25

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹14,656",05 May
1,IndiGo,BOM,BOM → DXB,19:35,21:00,2h 55m,non-stop,"₹15,391",05 May
2,SpiceJet,BOM,BOM → DXB,23:05,00:406 May,3h 5m,non-stop,"₹16,516",05 May
3,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹16,991",05 May
4,IndiGo,BOM,BOM → DXB,08:55,10:25,3h 0m,non-stop,"₹17,701",05 May
...,...,...,...,...,...,...,...,...,...
85,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹2,57,041",05 May
86,Multiple carrier,BOM,BOM → LHR → AUH,12:15,06:156 May,19h 30m,1 stop,"₹2,75,553",05 May
87,All Nippon,BOM,BOM → NRT → AUH,19:40,23:456 May,29h 35m,1 stop,"₹3,48,785",05 May
88,British Airways,BOM,BOM → LHR → DXB,13:10,07:306 May,19h 50m,1 stop,"₹3,60,122",05 May
89,Multiple carrier,BOM,BOM → LHR → AUH,13:10,06:156 May,18h 35m,1 stop,"₹4,75,391",05 May

In [109]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)  
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('7 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df26=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [110]:
df26['Date Of Journey'] = '06 May'
df26

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹14,062",06 May
1,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹14,064",06 May
2,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹14,905",06 May
3,IndiGo,BOM,BOM → DXB,02:25,04:00,3h 5m,non-stop,"₹14,971",06 May
4,GO FIRST,BOM,BOM → AUH,20:40,22:10,3h 0m,non-stop,"₹15,218",06 May
...,...,...,...,...,...,...,...,...,...
93,Multiple carrier,BOM,BOM → CAI → AUH,03:15,18:45,17h 0m,1 stop,"₹1,00,796",06 May
94,Multiple carrier,BOM,BOM → DEL → DOH → SHJ,06:30,16:35,11h 35m,2 stops,"₹1,22,330",06 May
95,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹1,29,631",06 May
96,British Airways,BOM,BOM → LHR → DXB,13:10,07:307 May,19h 50m,1 stop,"₹2,53,270",06 May
97,Swiss Intl Air,BOM,BOM → ZRH → DXB,05:15,21:30,17h 45m,1 stop,"₹4,31,459",06 May

In [111]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text)
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df27=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [112]:
df27['Date Of Journey'] = '07 May'
df27

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → DXB,02:25,04:00,3h 5m,non-stop,"₹17,701",07 May
1,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹18,284",07 May
2,Air India,BOM,BOM → CCJ → DXB,06:40,13:45,8h 35m,1 stop,"₹19,152",07 May
3,Air India,BOM,BOM → DXB,01:05,02:40,3h 5m,non-stop,"₹19,156",07 May
4,GO FIRST,BOM,BOM → AUH,20:40,22:10,3h 0m,non-stop,"₹19,418",07 May
...,...,...,...,...,...,...,...,...,...
95,Multiple carrier,BOM,BOM → DEL → DOH → SHJ,06:30,16:35,11h 35m,2 stops,"₹2,03,675",07 May
96,British Airways,BOM,BOM → LHR → DXB,13:10,07:308 May,19h 50m,1 stop,"₹2,53,270",07 May
97,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹2,57,041",07 May
98,Multiple carrier,BOM,BOM → LHR → AUH,13:10,06:158 May,18h 35m,1 stop,"₹3,41,894",07 May
99,All Nippon,BOM,BOM → NRT → AUH,19:40,23:458 May,29h 35m,1 stop,"₹3,48,785",07 May

In [113]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)   
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('9 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df28=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [114]:
df28['Date Of Journey'] = '08 May'
df28

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,GO FIRST,BOM,BOM → AUH,20:40,22:10,3h 0m,non-stop,"₹20,518",08 May
1,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹20,909",08 May
2,IndiGo,BOM,BOM → HYD → SHJ,19:55,21:559 May,27h 30m,1 stop,"₹21,113",08 May
3,Air India,BOM,BOM → DEL → DXB,19:00,16:559 May,23h 25m,1 stop,"₹21,777",08 May
4,IndiGo,BOM,BOM → DXB,02:25,04:00,3h 5m,non-stop,"₹22,006",08 May
...,...,...,...,...,...,...,...,...,...
102,Multiple carrier,BOM,BOM → BLR → DOH → SHJ,21:30,09:509 May,13h 50m,2 stops,"₹1,14,287",08 May
103,Multiple carrier,BOM,BOM → MAA → AUH,21:00,07:109 May,11h 40m,1 stop,"₹1,20,814",08 May
104,Multiple carrier,BOM,BOM → DEL → DOH → SHJ,06:30,16:35,11h 35m,2 stops,"₹1,22,330",08 May
105,Multiple carrier,BOM,BOM → BLR → DXB,07:00,12:45,7h 15m,1 stop,"₹1,95,766",08 May
106,Lufthansa,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,53,482",08 May

In [115]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('10 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df29=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [116]:
df29['Date Of Journey'] = '09 May'
df29

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹14,656",09 May
1,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹15,926",09 May
2,flydubai,BOM,BOM → DWC,05:10,06:55,3h 15m,non-stop,"₹16,400",09 May
3,SpiceJet,BOM,BOM → DWC,23:55,01:3010 May,3h 5m,non-stop,"₹16,516",09 May
4,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹16,768",09 May
...,...,...,...,...,...,...,...,...,...
96,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹2,57,041",09 May
97,Lufthansa,BOM,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹4,12,435",09 May
98,Swiss Intl Air,BOM,BOM → ZRH → DXB,05:15,20:45,17h 0m,1 stop,"₹4,31,459",09 May
99,Lufthansa,BOM,BOM → MUC → AUH,00:50,19:55,20h 35m,1 stop,"₹4,52,960",09 May
100,Lufthansa,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,53,482",09 May

In [117]:
a = []
air= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[1]/div/p")
for i in air:
    a.append(i.text)
s = []
sourc= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p/div[1]/span")
for i in sourc:
    s.append(i.text)    
r = []
rout= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[4]/p")
for i in rout:
    r.append(i.text)
dt = []
dtime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[1]/p")
for i in dtime:
    dt.append(i.text)
at = []
atime= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[2]/p")
for i in atime:
    at.append(i.text.replace('11 may',''))
u = []
dura= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[3]/p")
for i in dura:
    u.append(i.text)
ts = []
stop= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[2]/div/div[5]/p")
for i in stop:
    ts.append(i.text)
p = []
price= driver.find_elements_by_xpath("/html/body/div[1]/div/main/div/div/div[2]/div[2]/div[8]/div/div[1]/div[2]/div[3]/div[2]/div/p")
for i in price:
    p.append(i.text)

time.sleep(2)        
# creating dataframe
df30=pd.DataFrame({'Airline Name':a,'Source':s,'Route':r,'Departure Time':dt,'Arrival Time':at,'Duration':u,'Total Stops':ts,'Price':p})

In [118]:
df30['Date Of Journey'] = '10 May'
df30

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SpiceJet,BOM,BOM → DWC,23:55,01:3011 May,3h 5m,non-stop,"₹13,472",10 May
1,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹14,504",10 May
2,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹14,656",10 May
3,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹14,862",10 May
4,Air India,BOM,BOM → COK → DXB,05:30,13:35,9h 35m,1 stop,"₹15,057",10 May
...,...,...,...,...,...,...,...,...,...
97,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹1,29,631",10 May
98,British Airways,BOM,BOM → LHR → DXB,08:55,07:3011 May,24h 5m,1 stop,"₹2,12,339",10 May
99,All Nippon,BOM,BOM → NRT → AUH,19:40,23:4511 May,29h 35m,1 stop,"₹3,48,785",10 May
100,Lufthansa,BOM,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹4,12,435",10 May
101,Lufthansa,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,53,482",10 May

In [119]:
Flight4=pd.concat([df21,df22,df23,df24,df25,df26,df27,df28,df29,df30])
Flight4['Destination'] = 'DXB'
Flight4

,Airline Name,Source,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey,Destination
0,IndiGo,BOM,BOM → AUH,22:00,23:25,2h 55m,non-stop,"₹9,595",01 May,DXB
1,Air Arabia,BOM,BOM → SHJ,21:50,23:15,2h 55m,non-stop,"₹9,806",01 May,DXB
2,Air India Express,BOM,BOM → SHJ,02:20,04:00,3h 10m,non-stop,"₹9,989",01 May,DXB
3,Air Arabia,BOM,BOM → SHJ,04:55,06:20,2h 55m,non-stop,"₹10,232",01 May,DXB
4,SpiceJet,BOM,BOM → DXB,23:05,00:402 May,3h 5m,non-stop,"₹10,529",01 May,DXB
...,...,...,...,...,...,...,...,...,...,...
97,Multiple carrier,BOM,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹1,29,631",10 May,DXB
98,British Airways,BOM,BOM → LHR → DXB,08:55,07:3011 May,24h 5m,1 stop,"₹2,12,339",10 May,DXB
99,All Nippon,BOM,BOM → NRT → AUH,19:40,23:4511 May,29h 35m,1 stop,"₹3,48,785",10 May,DXB
100,Lufthansa,BOM,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹4,12,435",10 May,DXB
101,Lufthansa,BOM,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,53,482",10 May,DXB

In [136]:
FlightPrice=pd.concat([Flight,Flight1,Flight2,Flight3,Flight4])
FlightPrice

,Airline Name,Source,Destination,Route,Departure Time,Arrival Time,Duration,Total Stops,Price,Date Of Journey
0,SriLankan Airlines,BOM,LHR,BOM → CMB → LHR,03:10,20:00,21h 20m,1 stop,"₹64,734",30 Apr
1,Vistara,BOM,LHR,BOM → DEL → LHR,06:30,19:50,17h 50m,1 stop,"₹68,365",30 Apr
2,Vistara,BOM,LHR,BOM → DEL → LHR,08:45,19:50,15h 35m,1 stop,"₹68,770",30 Apr
3,Air India,BOM,LHR,BOM → IDR → DEL → LHR,07:05,19:00,16h 25m,2 stops,"₹69,655",30 Apr
4,Emirates,BOM,LGW,BOM → DXB → LGW,19:20,12:35,21h 45m,1 stop,"₹71,648",30 Apr
...,...,...,...,...,...,...,...,...,...,...
97,Multiple carrier,BOM,DXB,BOM → DEL → AUH,17:35,23:20,7h 15m,1 stop,"₹1,29,631",10 May
98,British Airways,BOM,DXB,BOM → LHR → DXB,08:55,07:3011 May,24h 5m,1 stop,"₹2,12,339",10 May
99,All Nippon,BOM,DXB,BOM → NRT → AUH,19:40,23:4511 May,29h 35m,1 stop,"₹3,48,785",10 May
100,Lufthansa,BOM,DXB,BOM → FRA → DXB,02:50,22:35,21h 15m,1 stop,"₹4,12,435",10 May
101,Lufthansa,BOM,DXB,BOM → FRA → AUH,02:50,19:20,18h 0m,1 stop,"₹4,53,482",10 May

In [138]:
FlightPrice.to_excel("FlightPricePredictionData.xlsx",sheet_name='FlightPricePrediction')

# Thank You...!!!